<?php
return [
    //Header
   "page_home_title_what"=>"What is Musica Dominus ?",
   "nav_home"=>"Home",
   "nav_us"=>"Us",
   "nav_write"=>"My writings",
   "nav_gallery"=>"Gallery",
   "nav_contact"=>"Contact",
   "nav_don"=>"Donation",
   "nav_lang"=>"Language",

   //banner
   "page_home_banner_p0"=>"Adventure",
   "page_home_banner_p1"=>"Inspiration",
   "page_home_banner_p2"=>"Passions",
   "page_home_banner_p3"=>"Reconnect to teaching true values.",
   "page_home_banner_p4"=>"CONTINUE",

   //body Home what
   'page_home_title_what'=>"What is Musica Dominus?",
   "page_home_subtitle_what"=>"The study of classical music is the best way, with prayer, to be able to overcome these inconveniences",
   "page_home_what_p1"=>"In all educational institutions and in many communities, we are witnessing acts of jealousy, harassment, intimidation. It is the most sensitive children who are very often the targets. even suffered this verbal and psychological violence as a kid. The study of classical music is the best way, with prayer, to be able to overcome these inconveniences by allowing the child to balance himself, to find his place in the world, develop by being able to assert themselves. As we have seen in the preceding chapters, excesses of violence and vulgarization are the signs of our decadent, materialistic and egocentric society.",
   "page_home_what_p2_b"=>"Musica Dominus",
   "page_home_what_p2"=>"is a way of reconnecting with the teaching of true values through the study of the Bible, suitable for children of all ages, on the theme of early music. I dedicate this teaching to the most deprived, to children who do not have the chance to have access to a quality musical education, especially not that of a classical instrument like the pianoforte.",
   "page_home_what_p3"=>"With intense attention and concentration, through meditation, the study and interpretation of minuets, sonatinas, arias by young beginners will be engraved and accessible in their deepest 'self', their true nature finally revealed by early music. This presence of the Spirit at their side and the path to success, this 'feeling of achievement', this is the illumination of a child sidelined by a bad orientation at school, in the community or simply, wandering in the street.",
    
   //body Home gallery
   "page_home_title_gallery"=>"Galleries",
   "page_home_subtitle_gallery"=>"I captured many of the wonderful moments I experienced in this beautiful adventure",
   "page_home_subtitle_what"=>"The study of classical music is the best way, with prayer, to be able to overcome these inconveniences",
   "page_home_more_gallery"=>"See more album",

   //body home write
   "page_home_title_write"=>"My writings",
   "page_home_subtitle_write"=>"The adventures of this beautiful project Musica Dominus inspired me to write and tell my experiences.",
   "page_home_title_p0_write"=>"Foreword",
   "page_home_date_p0_write"=>"April 27, 2016",
   "page_home_body_p0_write"=>"If music is a form of prayer, all harmony is a form of silence. We realize this so well when a noise bursts in the fervor of a summer evening in the Amazon. The whole nature was vibrant, all life chimed in the crimson intoxication of the light filtered through the treetops.The rays of light which crossed them, celebrated in fiery antiphons the ecstasy of the sun...And suddenly piercing cries, those of the monkeys howlers broke all this incantation. A bickering, an argument, a cry of love revealed to us the majesty of silence.",
   "page_home_title_p1_write"=>"I.Introduction",
   "page_home_date_p1_write"=>"April 27, 2016",
   "page_home_body_p1_write"=>"Travelling is not a reaction of revolt of the world but more the need to breathe! It even seems that a trip is not decided immediately or rather is not programmed! We unfold our road map, that of all America, the heart races, the decision and even the direction, seems to be taken very often before finding the real reason.
   At the time, in the 80s, I landed on the west coast of the United States, full of ambition. Before, I led a very pleasant life, living on a small 25-foot sailboat in the port of Antibes in the south of France. As soon as the mistral started to blow, strongly sweeping the gray clouds and the swell coming to us from the Gulf of Genoa, we took my girlfriend and I, the helm towards Saint-Tropez or the islands of Hyères. To earn a living, we had a very modest little restaurant.",
   "page_home_title_p2_write"=>"II Spiritual Meaning of Musica Dominus",
   "page_home_date_p2_write"=>"April 27, 2016",
   "page_home_body_p2_write"=>"If I received a traditional Catholic education, I admit that I did not really have a very deep conviction in my youth. I respected and followed this religion taught by my family. My grandmother was a musician, she took me to the Queen Elisabeth competitions in Brussels. I was amazed by the piano concerts of Ludwig von Beethoven interpreted by Emil Gilels, the nocturnes and Polonaises of Frederic Chopin interpreted by Mauricio Polini and others by Tchaikovsky, played with emphasis by this Russian pianist whose name I have forgotten. I tried to reproduce these extraordinary sounds on the black piano of my grandfather's mansion. I discovered the chords that resonated thanks to the high ceilings of this stone residence with its marble columns.",
   "page_home_more_write"=>"Learn More",

   //US
   "page_us_body_p0"=>"In all educational institutions and in many communities, we are witnessing acts of jealousy, harassment, intimidation. It is the most sensitive children who are very often the targets. even suffered this verbal and psychological violence as a kid. The study of classical music is the best way, with prayer, to be able to overcome these inconveniences by allowing the child to balance himself, to find his place in the world, develop by being able to assert themselves. As we have seen in the preceding chapters, excesses of violence and vulgarization are the signs of our decadent, materialistic and egocentric society.",
   "page_us_body_p1"=>"is a way of reconnecting with the teaching of true values through the study of the Bible, suitable for children of all ages, on the theme of early music. I dedicate this teaching to the most deprived, to children who do not have the chance to have access to a quality musical education, especially not that of a classical instrument like the pianoforte.",
   "page_us_body_p2"=>"With intense attention and concentration, through meditation, the study and interpretation of minuets, sonatinas, arias by young beginners will be engraved and accessible in their deepest 'self', their true nature finally revealed by early music. This presence of the Spirit at their side and the path to success, this 'feeling of achievement', this is the illumination of a child sidelined by a bad orientation at school, in the community or simply, wandering in the street.",
   "page_us_body_p3"=>"I wanted to end by specifying that the piano, the king of instruments, brings together in itself, in harmony, the instruments used by King David and his court during the prayers of the psalms. Let us recall that in the Jewish liturgy of the Temple, the cadence commanded by the instruments seemed to take more place than the melody. The music served above all to give rhythm to the various movements of the celebration with the drum or the tambourine as well as the cymbals. The horn, made with a horn of goat, serving to announce the presence of the Lord, blending harmoniously with the lyre, played by David.",
   "page_us_body_p4"=>"All peoples clap your hands! God ascends in acclamation, Yahweh in the sound of the horn! Psalm (47) 46, 1 - 6",
   "page_us_body_p5"=>"The modern acoustic piano is a struck string instrument, the harmonic board must be of the best quality of wood. The metronome, marking the cadence is essential and the three pedals allow the young musician to learn to s 'express, without excess, from piano to forte through concentration, meditation and daily study.",
   "page_us_body_p6"=>"Please help us spread the message.",
   "page_us_body_p7"=>"Your donations are welcome and will be invested in this goal.",

   "page_us_title_about"=>"About Me",
   "page_us_subtitle_about"=>"There is no love to be taken, there is love to be received. There is as much love to be received as there is to be given and what Christianity does , is that everything can be experienced in the way of receiving and giving. ",
   "page_us_p00_about"=>"Hello, first of all I wanted to introduce myself:",
   "page_us_p0_about"=>"Vincent Cambier",
   "page_us_p1_about"=>"born December 10, 1057, in Ronse, a small town in the kingdom of Belgium, located a few kilometers from the French border, the towns of Roubaix, Tourcoing and Lille being the closest. Traditional Catholic education, Greek Latin at the Jesuit college.",
   "page_us_p2_about"=>"The particle 'de La Lozerie' comes from our origins, when we were knighted in the 14th century. I use it on all my travel adventure books, not out of snobbery or pretension, only that it's prettier and the name Cambier is too hard to pronounce in America.",
   "page_us_p3_about"=>"Musical youth thanks to my maternal grandmother: Lutgarde, originally from Tongres, in Limburg, near the German border.",
   "page_us_p4_about"=>"At the age of 20, I left Europe for San Diego, California, in the United States with Béatrice, the young and pretty waitress of the restaurant we had created in Antibes, in the south of France. the rest of my youth was deeply influenced by the North American culture of the '80s': worship of the body, plastic beauty and materialistic life. Very quickly I became the best salesman of a marriage agency, at the time when the computers didn't exist. I drove a Cadillac and traveled between Newport Beach, Hollywood, Beverly Hills and La Jolla, the jewel of California, a seaside resort north of San Diego where I had my sailboat, a 30-foot sloop , at the port of Mission Bay.",
   "page_us_p5_about"=>"The 25-foot Jeannot, anchored in the Vauban port of Antibes where we slept, Béatrice and I, lulled by the waves of the Mediterranean was already far away, just like her, whom I abandoned, preferring plastic beauties of young Americans.",
   "page_us_p6_about"=>"At the age of 40, I was a journalist, writer and even salesman for a wine and gastronomy magazine in Cannes, in the Alpes Maritimes in France. A few years later, I was invited by the national airline of Chile as well as by some large merchants producing wines from this region of the new world. Comfortably installed in the luxurious suite on the top floor of the Crowne Plaza hotel in Santiago de Chile, where I played billiards with the Swiss chef, I was able to taste the exotic cuisine, amazed by the young Latin ladies with golden complexions from the Bella Vista district, the bohemian district of the capital.Following this report on wines from the new world, I returned to California, invited by the association Napa and Sonoma Valley wines.",
   "page_us_p7_about"=>"Later, I settled in the state of Arizona, in the United States, where I created my own line of home fragrances and cosmetics: 'La Lozerie en Provence', manufactured by the Grangeon family established in St Rémy de Provence. These were the best years: ten years of work without taking vacations, shared between the south of France and all of North America. On board the Dodge RAM and its unforgettable 5 liter V8 engine, which effortlessly towed a 10 x 6 foot Pace American trailer, which served as both an office and a berth. New England, Georgia, Texas, the Midwest, Chicago and Illinois, Michigan, Colorado and Utah, the Canadian border, Seattle and Vancouver, all of California that I knew well, Arizona and Louisiana where I was able to speak French with the last black Americans from New Orleans, La Fayette and t Bâton Rouge, African-American friends who have preserved the true values of the past and the culture of their ancestors.",
   "page_us_p8_about"=>"The economic crisis of 2018 and 2019, the fall of the two largest banks and mortgage credit in the United States marked the end of the American dream, which had been created by the Clinton era and their financial mirage In a few weeks, I lost a third of my customers who could no longer honor the invoices for their orders placed at 'La Lozerie en Provence' which lost a little over a hundred thousand dollars. system that was killing small businessmen, now the bigwigs of multinationals, I decided to cross the border into Mexico, sending the bounced checks, 'bad checks' and unpaid invoices flying out of the open window of the Dodge . So much the worse for ecology.",
   "page_us_p9_about"=>"In a few months, since that of Nogales in Mexico, I will have crossed ten borders: Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Colombia, Ecuador, Peru, Chile or the V8 engine has overheated in the Atacama desert. Repaired in Paraguay, by an Argentinian mechanic, I could continue a trip that seemed to never want to end. Crossing Brazil, French Guyana, Suriname, Guyana, Boa Vista: the gateway to the Amazon, northern Brazil, crossing Venezuela in the midst of an economic crisis, I reached, with great difficulty, Cucuta, in Colombia on the other side! A third trip made me discover Ayacucho, Arequipa in Peru, Bolivia of Amerindian culture, Lake Titicaca, Jujuy in Argentina, Tilcara, San Juan, the border road of the Andes: el paso de Jama, Antofagasta, Arica in Chile, Lake Chungara, San Pedro and the Azapa Valley where Peruvian mechanics were able to assemble the new motorhome, coming from the United States, during the two years of the pandemic when the borders were closed. Thanks to the hospitality of Niksa Bezmalinovic, one of the last farmers in this desert valley where I was able to live in the simple trailer which had also chosen this desert olive grove for its total renovation. Thus was born the motorhome you see in the photo: a Ford truck from Valparaiso, with mixed registration from Chile and Arizona, USA, where it was manufactured.",
   "page_us_p10_about"=>"From San Diego, USA to Sao Francisco, Brasil:",
   "page_us_p11_about"=>"Throughout these trips, I endured so many difficulties: broken spring blades, two lost wheels, rolling alone! In the immensity of the great Venezuelan savannah, mudguards ripped open and smashed by shocks, blown tires, cylinder head gasket which twice fried two engines: the original Ram engine from Dodge Chrysler, an MWM turbo diesel installed in Paraguay, shredded belts… The hardest moments were the breakage on the dirt track between the Amazon of Guyana and Brazil, the four wheels of the trailer stolen on Christmas Eve from the parking lot of the parish of San Felix, in the center of Venezuela, the controls of the military police of Brazil and the corrupt Guarda Nacional of Venezuela, the “control” stops of the paramilitaries of El Salvador, the roads without security barriers crisscrossing and overlooking the Pacific in Peru, the demonstrations of the 2009s in Honduras…the hinged roads people from Mexico…and the kids who beg because they are hungry. But what makes the strength of a traveler is this inner will that always pushes you to move forward, to go further.",
   "page_us_p12_about"=>"These years of adventurous travel taught me that in San Diego, California, I was not a free man. I was a slave to my materialistic, selfish life. more and more beautiful. Now that I have lost my earthly father, I know that our spiritual Father, the Creator of all this universe, did not create freedom for us, for he created Man with the freedom to free himself. True freedom is not found on the beaches of Panama or those of Costa Rica, nor in the great savannah, in the arms of a pretty Venezuelan. Freedom is freedom only if we create it for the voice of nature constantly resounds in man a call to live not for God and for other men but for himself alone, selfishly, like the other beings of nature who live according to their instinct. documenting myself and by reading my father's spiritual books, written by François Varillon and Maurice Zundel, I understood that there is n the man (and the woman) a double force: on the one hand, a force of gravity and inertia which invites him to give up being a free man and pushes him to live like the other beings of the world who have no freedom to build. And on the other hand, an upward force that invites him to build his freedom that God, by grace, will give access to his own freedom. True freedom is found in divinity, welcoming Christ into one's heart by living according to his example, by denying oneself. Two great examples of free men were Francis of Assisi or Charles de Foucault, who led their lives by sharing with others and living for others. So few of us simple sinners can reach such a level of holiness and divinity, it is necessary for us to modify our behavior towards others. Because the essence of sin is to trigger a train of waves that disrupt human relationships. Every bad action or thought is a provocation to the evil that we deposit in the conscience of others.",
   "page_us_p13_about"=>"There is no love to take, while there is love to receive. There is as much love to receive as to give and what makes Christianity , is that everything can be lived in the mode of welcoming and giving.",
   "page_us_p14_about"=>"To those who have difficulty, to live according to these precepts in our everyday life, this brutal society, decadent and corrupted by vice and selfishness, the option of going to live in community is to be explored.",
   "page_us_p15_about"=>"Personally, as a travel writer, I discovered freedom by being able to give more 'of myself', in tasks as a voluntary language teacher in the Misak Amerindian communities of Colombia, the Quichuas of Ecuador , from Peru, the Guarani from Paraguay, from Venezuela, the indigenous kids from the Amazon in Guyana, at Boa Vista in northern Brazil, helping the Franciscan friars in Rio de Janeiro as well as in Panama, in the coffee communities of the Barú volcano.",
   "page_us_p16_about"=>"If I study and teach baroque music, also called sacred music, it is because the classical piano has become the essential vector of my close relationship with the Heavenly Father. For me, it is the transcendental form to the Creator.",
   "page_us_p17_about"=>"By having studied, without deepening them, the oriental techniques of medicine, I was able to understand that the way of eating plays a big role in the behavior of the human being.",
   "page_us_p18_about"=>"You are what you eat",
   "page_us_p19_about"=>"…You are what you eat, a well-known saying of a Greek philosopher. I will add: according to what you eat, and the sober way of eating, as in the macrobiotic or vegan diet , builds a space of peace within you. Everything on earth and in the universe exists in complementary opposition. By living in a world bathed in extreme acidity (degraded food, vulgarity, selfishness, acoustic contamination, air pollution , water and spirit), it is necessary to balance by eating cereals, plants, fruits, which I will name: alkaline diet. I recommend a diet of 80% alkaline (YIN) and 20 % acid (YANG). Vegetarian human beings will be more easily recognized in their non-aggressive way of life and their relationship with others.",
   "page_us_p20_about"=> "In our world, does not the symbol remain the cross? Man torn between an ascending force, God's call to share love and a force that pulls him down , the path of the bondage of his so-called freedom. As well as a balance between YIN and YANG, alteration between alkaline and acid.",


   //Write
   "page_home_title_p3_write"=>"III. Reasons to study early music at the piano",
   "page_home_date_p3_write"=>"April 27, 2016",
   "page_home_body_p3_write"=>"Why study at the piano, works written by baroque composers, so old, straddling the Renaissance and the Classical. Harmonic balance. For beginners, mostly children: it forces you to do function the two parts of the brain.The left part of the brain corresponds to logic, it will process the functional, mathematical aspect of music, such as the division of sounds into half notes, quarter notes, eighth notes, semi eighth notes etc... The right part of the brain will deal with art, melody, singing! Because let's not forget that playing the piano is simply making your instrument sing! By managing to coordinate the two hands, we will achieve harmony. It is almost a matter of a struggle between the head (left hand) and the heart (right hand) between melodic expansion and rhythmic tension, between structure and reverie. Most interesting is the reversal, passing the melody to the left hand and the rhythm to the right…",
   "page_home_title_p4_write"=>"IV. Music therapy and psychology",
   "page_home_date_p4_write"=>"April 27, 2016",
   "page_home_body_p4_write"=>"This information was provided to us by newspapers in the United States. Half an hour of classical music a day is compulsory for all children in Florida, United States. Nicknamed Beethoven's Babies Bill , law 660 is not only intended to help children fall asleep at nap time, it also aims to stimulate their brain development in a harmonious way... In France, the beneficial action of music is not completely unknown.In the Parisian hospitals Armand-Trousseau and Necker, the infant pre-anesthesia rooms become real concert halls: children, parents and nursing staff can manipulate instruments, discover sounds, improvise or listen cassettes After this conditioning, a musician accompanies the child to the operating room by resonating in the maze of corridors, elevators and other unknown cold places, harmonious and reassuring sounds . The results are conclusive since music plays a positive role in the success of anesthesia and helps children better cope with the trauma of their hospital stay.",
   "page_home_title_p5_write"=>"V. My career as a teacher",
   "page_home_date_p5_write"=>"April 27, 2016",
   "page_home_body_p5_write"=>"My journey as a volunteer teacher in Native American communities. In North America, I was fascinated by the Sioux, the Navajos, in the Great Plains, the Southeastern Cheyenne, the Apaches in the southwest. I was able to visit the reservations, exchange ideas with many of them. They speak as many different dialects there as the entire Amerindian population of Colombia. Unlike the tourist air travelers who know much more the capitals of the countries they visit, the airport and the comfortable international hotels being close; personally, humble road traveler, without schedule, without constraints, not understanding well the objective of the organized trips, I slowly began to feel invaded by this gentle primitive savagery. I felt closer to the natives than to the white majority of these small Central American countries. With them, I learned to live as simply as possible, in harmony tact with nature and trying to taste everything, especially silence. I don't like to talk about poverty; but live off the fresh produce of the land, to the rhythm of the seasons, from its good or bad harvests. The harshness of the conditions and the vagaries of the climate make you want to cry justice!",

   //footer
   "footer_text"=>"We need your support a donation to keep this project going.",
   "footer_button"=>"Support us",
   "footer_copyright"=>"© Musica Dominus. 2022 All rights reserved.",

];