<?php
return [

   //Header
   'page_home_title_what'=>"Qu'est-ce que Musica Dominus ?", 
   "nav_home"=>"Accueil",
   "nav_us"=>"À propos",
   "nav_write"=>"Mes écrits",
   "nav_gallery"=>"Galeries",
   "nav_contact"=>"Contact",
   "nav_don"=>"Don",
   "nav_lang"=>"Langue", 
   
   //banner
   "page_home_banner_p0"=>"Aventure",
   "page_home_banner_p1"=>"Inspiration",
   "page_home_banner_p2"=>"Passions",
   "page_home_banner_p3"=>"Reconnecter à l'enseignement aux vraies valeurs.",
   "page_home_banner_p4"=>"CONTINUER", 
   

   //body Home what
   'page_home_title_what'=>"Qu'est-ce que Musica Dominus ?", 
   "page_home_subtitle_what"=>"L'étude de la musique classique est le meilleur moyen, avec la prière, de pouvoir surmonter ces désagréments",
   "page_home_what_p1"=>"Dans toutes les institutions scolaires et dans bien des communautés, on assiste à des actes de jalousie, harcèlement, d’intimidation. Ce sont les enfants les plus sensibles qui sont bien souvent les cibles. J’ai moi-même subis ces violences verbales et psychologiques étant gosse. L’étude de la musique classique est le meilleur moyen, avec la prière, de pouvoir surmonter ces désagréments en permettant à l’enfant de s’équilibrer, de trouver sa place dans le monde, se développer en pouvant s’affirmer. Comme nous l’avons vu dans les chapitres précédents, les excès de violence et la vulgarisation sont les signes de notre société décadente, matérialiste et égocentriste.",
   "page_home_what_p2_b"=>"Musica Dominus",
   "page_home_what_p2"=>"est une manière de renouer avec l’enseignement des vraies valeurs par l’étude de la Bible, adaptée à l’enfant de tous les âges, sur thème de la musique ancienne. Cet enseignement je le dédie aux plus démunis, aux enfants qui n’ont pas la chance d’avoir accès une éducation musicale de qualité, surtout pas celle d’un instrument classique comme le pianoforte.",
   "page_home_what_p3"=>"Avec une attention et concentration intenses, grâce à la méditation, l’étude et l’interprétation des menuets, sonatines, arias par les jeunes débutants, sera gravée et accessible dans leur « moi » le plus profond, leur véritable nature enfin révélée par la musique ancienne. Cette présence de l’Esprit à leurs côtés et l’acheminement vers le succès, cette « sensation de réalisation », c’est cela l’illumination d’un gamin mis à l’écart par une mauvaise orientation à l’école, en communauté ou simplement, errant dans la rue.",
  
   //body Home gallery
   "page_home_title_gallery"=>"Galeries",
   "page_home_subtitle_gallery"=>"J'ai capturé une grande partie des merveilleux moments que j'ai vécus dans cette belle aventure",
   "page_home_subtitle_what"=>"L'étude de la musique classique est le meilleur moyen, avec la prière, de pouvoir surmonter ces désagréments",
   "page_home_more_gallery"=>"Voir plus d'album",

   //body home write
   "page_home_title_write"=>"Mes écrits",
   "page_home_subtitle_write"=>"Les aventures de ce beau projet Musica Dominus m'ont inspiré pour écrire et raconter mes expériences.",
   "page_home_title_p0_write"=>"Avant-Propos",
   "page_home_date_p0_write"=>"27 Avril 2016",
   "page_home_body_p0_write"=>"Si la musique est une forme de prière, toute harmonie est une forme de silence. On s’en rends si bien compte quand un bruit éclate dans la ferveur d’un soir d’été en Amazonie. Toute la nature était vibrante, toute vie carillonnait dans l’ivresse empourprée de la lumière tamisée par la cime des arbres. Les rayons de lumière qui les traversaient, célébraient en antiennes de feu l’extase du soleil…Et soudain des cris perçants, ceux des singes hurleurs ont rompu toute cette incantation. Une chamaillerie, une dispute, un cri d’amour nous a révélé la majesté du silence.",
   "page_home_title_p1_write"=>"I. Introduction",
   "page_home_date_p1_write"=>"27 Avril 2016",
   "page_home_body_p1_write"=>"Voyager n’est pas une réaction de révolte du monde mais plus le besoin de respirer! Il semble même qu’un voyage ne se décide pas de suite ou plutôt ne se programme pas ! On déplie sa carte routière, celle de toute l’Amérique, le cœur s’emballe ; la décision et même la direction, semble se prendre bien souvent avant d’en trouver la vraie raison. 
   A l’époque, dans les années 80, je débarquais sur la côte ouest des Etats Unis, plein d’ambition. Avant, je menais une vie bien agréable, vivant sur un petit voilier de 25 pieds au port d’Antibes dans le sud de la France. Dès que le mistral se mettait à souffler, balayant fortement les nuages gris et la houle nous venant du golfe de Gêne, nous prenions ma petite amie et moi, la barre vers Saint-Tropez ou les iles d’Hyères. Pour gagner notre vie, nous avions un petit restaurant bien modeste.",
   "page_home_title_p2_write"=>"II Signification spirituelle de Musica Dominus ",
   "page_home_date_p2_write"=>"27 Avril 2016",
   "page_home_body_p2_write"=>"Si j’ai reçu une éducation traditionnelle catholique, j’avoue ne pas vraiment avoir eu de conviction très profonde dans ma jeunesse. Je respectais et suivais cette religion enseignée par ma famille. Ma grand-mère était musicienne, elle m’emmenait aux concours reine Elisabeth à Bruxelles. J’ai été émerveillé par les concerts pour piano de Ludwig von Beethoven interprété par Emil Gilels, les nocturnes et polonaises de Fréderic Chopin interprété par Mauricio Polini et autre de Tchaïkovski, joué avec emphase par ce pianiste russe dont j’ai oublié le nom. Je tâchais de reproduire ces sons extraordinaires sur le piano noir de la maison de maitre de mon grand-père. Je découvrais les accords qui résonnaient grâce aux plafonds hauts de cette demeure en pierre avec ses colonnes de marbre.",
   "page_home_more_write"=>"En savoir plus",

   //US
   "page_us_body_p0"=>"Dans toutes les institutions scolaires et dans bien des communautés, on assiste à des actes de jalousie, harcèlement, d’intimidation. Ce sont les enfants les plus sensibles qui sont bien souvent les cibles. J’ai moi-même subis ces violences verbales et psychologiques étant gosse. L’étude de la musique classique est le meilleur moyen, avec la prière, de pouvoir surmonter ces désagréments en permettant à l’enfant de s’équilibrer, de trouver sa place dans le monde, se développer en pouvant s’affirmer. Comme nous l’avons vu dans les chapitres précédents, les excès de violence et la vulgarisation sont les signes de notre société décadente, matérialiste et égocentriste.",
   "page_us_body_p1"=>"est une manière de renouer avec l’enseignement des vraies valeurs par l’étude de la Bible, adaptée à l’enfant de tous les âges, sur thème de la musique ancienne. Cet enseignement je le dédie aux plus démunis, aux enfants qui n’ont pas la chance d’avoir accès une éducation musicale de qualité, surtout pas celle d’un instrument classique comme le pianoforte.",
   "page_us_body_p2"=>"Avec une attention et concentration intenses, grâce à la méditation, l’étude et l’interprétation des menuets, sonatines, arias par les jeunes débutants, sera gravée et accessible dans leur « moi » le plus profond, leur véritable nature enfin révélée par la musique ancienne. Cette présence de l’Esprit à leurs côtés et l’acheminement vers le succès, cette « sensation de réalisation », c’est cela l’illumination d’un gamin mis à l’écart par une mauvaise orientation à l’école, en communauté ou simplement, errant dans la rue.",
   "page_us_body_p3"=>"Je voulais terminer en précisant que le piano, le roi des instruments, rassemble en lui seul, en harmonie, les instruments utilisés par le roi David et sa cour lors des prières des psaumes. Rappelons que dans la liturgie juive du Temple, la cadence commandée par les instruments semblait prendre plus de place que la mélodie. La musique servait avant tout à rythmer les divers mouvements de la célébration avec le tambour ou le tambourin ainsi que les cymbales. Le cor, fabriqué avec une corne de bouc, servant à annoncer la présence du Seigneur, se mêlant harmonieusement avec la lyre, jouée par David.",
   "page_us_body_p4"=>"Tous les peuples battez des mains ! Dieu monte parmi l’acclamation, Yahvé aux éclats du cor ! Psaume (47) 46, 1 - 6",
   "page_us_body_p5"=>"Le piano moderne acoustique est un instrument à cordes frappées, la table harmonique doit être de la meilleure qualité de bois. Le métronome, marquant la cadence est indispensable et les trois pédales permettent au jeune musicien d’apprendre à s’exprimer, sans excès, de piano à forte par la concentration, la méditation et l’étude quotidienne.",
   "page_us_body_p6"=>"Merci de nous aider à transmettre le message.",
   "page_us_body_p7"=>"Vos dons sont les bienvenus et seront investis dans cet objectif.",

   "page_us_title_about"=>"À propos de moi",
   "page_us_subtitle_about"=>"Il n'y a pas d'amour à prendre, alors qu'il y a de l'amour à recevoir. Il y a autant d'amour à recevoir qu'à donner et ce que fait le christianisme, c'est que tout peut être vécu dans la manière de recevoir et de donner. ",
   "page_us_p00_about"=>"Bonjour, avant tout je voulais me présenter :",
   "page_us_p0_about"=>"Vincent Cambier ",
   "page_us_p1_about"=>"né le dix décembre 1057, à Renaix, petite ville du royaume de Belgique, située à quelques kilomètres de la frontière française, les villes de Roubaix, Tourcoing et Lille étant les plus proches. Éducation traditionnelle catholique, latin grec au collège jésuite.",
   "page_us_p2_about"=>"La particule « de La Lozerie » provient de nos origines, quand nous fûmes anoblis chevalier au XIVème siècle. Je l’utilise sur tous mes livres d’aventure de voyages, non pas par snobisme ou prétention, seulement que c’est plus joli et le nom Cambier est trop difficile à prononcer en Amérique.",
   "page_us_p3_about"=>"Jeunesse musicale grâce à ma grand-mère maternelle : Lutgarde, originaire de Tongres, dans le Limbourg, proche de la frontière allemande.",
   "page_us_p4_about"=>"A 20 ans, je quitte l’Europe vers San Diego, Californie, aux États-Unis avec Béatrice, la jeune et jolie serveuse du restaurant que nous avions créé à Antibes, dans le sud de la France. Tout le restant de ma jeunesse a été profondément influencé par la culture nord-américaine des « années 80 » : culte du corps, beauté plastique et vie matérialiste. Très vite je devins meilleur vendeur d’une agence matrimoniale, à l’époque où l'informatique n’existait pas. Je roulais en Cadillac et voyageais entre Newport Beach, Hollywood, Beverly Hills et La Jolla, le joyau de la Californie, une station balnéaire au nord de San Diego ou j’avais mon voilier, un sloop de 30 pieds, au port de Mission Bay.",
   "page_us_p5_about"=>"Le Jeannot de 25 pieds, ancré au port Vauban d’Antibes ou nous dormions, Béatrice et moi, bercé par le flot de la Méditerranée était déjà loin, tout comme elle, que j’ai abandonné, préférant les beautés plastiques des jeunes américaines.",
   "page_us_p6_about"=>"A 40 ans, j’étais journaliste, écrivain  et même vendeur de publicités pour un magazine de vins et de gastronomie à Cannes, dans les Alpes Maritimes en France. Quelques années plus tard, je fus invité par la ligne aérienne nationale du Chili ainsi que par quelques gros négociants producteurs de vins de cette région du nouveau monde. Confortablement installé dans la suite luxueuse au dernier étage de l’hôtel Crowne Plaza de Santiago du Chili, ou je jouais au billard avec le chef suisse, j’ai pu goûter à la cuisine exotique, émerveillé par les jeunes latines au teint doré du quartier de Bella Vista, le quartier bohême de la capitale. Suite à ce reportage des vins du nouveau monde je retournais en Californie, invité par l’association des vins de Napa et Sonoma Valley.",
   "page_us_p7_about"=>"Plus tard,  je m’établissais dans l’état d’Arizona, aux États-Unis, ou j’ai créé ma propre ligne de parfums d’ambiance et de cosmétiques : « La Lozerie en Provence », fabriqué par la famille Grangeon établie à St Rémy de Provence. Ce furent les plus belles années : dix ans de travail sans prendre de vacances, partagé entre le sud de la France et tout le territoire nord-américain. A bord de la Dodge RAM et son inoubliable moteur V8 de 5 litres, qui tirait sans peine une remorque Pace American de 10 pieds sur six, qui me servait à la fois de bureau et de couchette. Avec ce véhicule  roulant les interstates, j’ai connu presque tous les états : du New England, de Georgie, du Texas, du Midwest, de Chicago et Illinois, du Michigan, du Colorado et de l’Utah, la frontière du Canada, Seatle et Vancouver, toute la Californie que je connaissais bien, l’Arizona et la Louisiane ou j’ai pu parler le français avec les derniers noirs américains de Nouvelle Orléans, de La Fayette et Bâton Rouge, des amis afro-américains ayant conservé les vraies valeurs du passé et la culture de leurs ancêtres.",
   "page_us_p8_about"=>"La crise économique des années 2018 et 2019, la chute des deux plus importantes banques et crédit immobiliers des États-Unis ont marqué la fin du rêve américain, qu’avaient créé l’époque des Clinton et leur mirage financier. En quelques semaines, je perdais le tiers de ma clientèle qui ne pouvait plus honorer les factures de leurs commandes passées à « La Lozerie en Provence » qui perdait un peu plus de cent mille dollars.  Trop dur à remonter la pente…Écœuré par un système qui tuait les petits businessmen, maintenant les gros bonnets des multinationales, je décidais de traverser la frontière du Mexique, en envoyant par la fenêtre ouverte de la Dodge, s’envoler les bounced checks, « les chèques en bois » et les factures impayées. Tant pis pour l’écologie.",
   "page_us_p9_about"=>"En quelques mois, depuis celle de Nogales au Mexique, j’aurai traversé dix frontières : Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Colombie, Équateur, Pérou, Chili ou le moteur V8 a surchauffé dans le désert de l’Atacama. Réparé au Paraguay, par un mécanicien argentin, je pouvais continuer un voyage qui semblait ne jamais vouloir se terminer. Traversant le Brésil, la Guyane française, le Suriname, le Guyana, Boa Vista : la porte d’entrée de l’Amazonie, le nord du Brésil, traversée du Venezuela en pleine crise économique, j’atteignais, avec grosses difficultés, Cucuta, en Colombie de l’autre côté! Un troisième voyage m'a fait découvrir Ayacucho, Aréquipa au Pérou, la Bolivie de culture amérindienne, le lac Titicaca, Jujuy en Argentine, Tilcara, San Juan, la route frontalière des Andes : el paso de Jama, Antofagasta, Arica au Chili, le lac Chungara, San Pedro et la vallée de Azapa ou des mécaniciens péruviens ont pu monter le nouveau motor-home, venant des États-Unis, durant les deux années de pandémie ou les frontières étaient fermées. Grâce à l’hospitalité de Niksa Bezmalinovic, un des derniers agriculteurs de cette vallée du désert ou j’ai pu vivre dans la simple remorque qui elle aussi avait choisi cette oliveraie du désert pour sa totale rénovation. Ainsi est née le motor-home que vous voyez en photo : un camion Ford de Valparaiso, à l'immatriculation mixte du Chili et de l’Arizona, USA, ou elle a été fabriquée.",
   "page_us_p10_about"=>"De San Diego, USA a Sao Francisco, Brasil:",
   "page_us_p11_about"=>"Tout au long de ces voyages, j’ai enduré tellement de difficultés : de la casse de lames ressorts, deux pertes de roues, roulant toute seule! Dans l’immensité de la grande savane vénézuélienne, de gardes boue éventrés et par choques enfoncés, de pneus explosés, joint de culasse qui ont par deux fois grillé deux moteurs : le moteur original Ram de Dodge Chrysler, d’un turbo diesel MWM installé au Paraguay, de courroies déchiquetées…Les moments les plus durs furent la casse sur la piste de terre entre l’Amazonie de Guyane et du Brésil, les quatre roues de la remorque volées la veille de la noël sur le parking de la paroisse de San Felix, au centre du Venezuela, les contrôles de la police militaire du Brésil et la Guarda Nacional corrompue du Venezuela, les arrêts de « contrôle » des paramilitaires du Salvador, les routes sans barrière de sécurité sillonnant et surplombant le pacifique au Pérou, les manifestations des années 2009 dans le Honduras…les routes à charnières du Mexique…et les gosses qui mendient parce qu’ils ont faim. Mais ce qui fait la force d’un voyageur est cette volonté intérieure qui toujours vous pousse à avancer, à aller plus loin.",
   "page_us_p12_about"=>"Ces années de voyages d’aventures m’ont appris qu’à San Diego, en Californie, je n’étais pas un homme libre. J’étais esclave de ma vie matérialiste, égoïste. Du « toujours vouloir plus et plus beau ». Maintenant que j’ai perdu mon père terrestre, je sais que notre Père spirituel, le Créateur de tout cet univers, ne nous a pas fabriqué une liberté, car il a créé l’Homme avec la liberté de se rendre libre lui-même. La vraie liberté ne se trouve pas sur les plages de Panama ou celles du Costa Rica, ni dans la grande savane, dans les bras d’une jolie vénézuélienne. La liberté n’est liberté que si on la crée soi-même. Car la voix de la nature fait retentir constamment en l’homme un appel à vivre non pour Dieu et pour les autres hommes mais pour lui seul, égoïstement, comme les autres êtres de la nature qui vivent selon leur instinct. En me documentant et en lisant les livres spirituels de mon père, écris par François Varillon et Maurice Zundel, j’ai compris qu’il y a en l’homme (et la femme) une double force : d’une part, une force de pesanteur et d’inertie qui l’invite à renoncer à être un homme libre et le pousse à vivre comme les autres êtres du monde qui n’ont pas de liberté a construire. Et d’autre part, une force ascensionnelle  qui l’invite à construire sa liberté que Dieu, par grâce, fera accéder jusqu’à sa propre liberté. La vraie liberté se trouve dans la divinité, en accueillant le Christ dans son cœur en vivant selon son exemple, en renonçant à soi-même. Deux grands exemples d’hommes libres furent François d’Assise ou Charles de Foucault, qui menaient leurs vies en partageant avec les autres et en vivant pour les autres. Si bien peu de nous, simples pécheurs, pouvons atteindre un tel niveau de sainteté et de divinité, il nous est nécessaire de modifier notre comportement envers autrui. Car le propre du péché est de déclencher un  train d’ondes qui perturbent les relations humaines. Toute mauvaise action ou pensée est une provocation au mal que nous déposons dans la conscience d’autrui.",
   "page_us_p13_about"=>"Il n’y a pas d’amour à prendre, tandis qu’il y a de l’amour à accueillir. Il y a autant d’amour à accueillir qu’à donner et ce qui fait le christianisme, c’est que tout peut-être vécu sur le mode de l’accueil et du don.",
   "page_us_p14_about"=>"A ceux qui auraient des difficultés à vivre selon ces préceptes dans notre vie de tous les jours, cette société brutale, décadente et corrompue par le vice et l’égoïsme, l’option d’aller vivre en communauté est à explorer.",
   "page_us_p15_about"=>"Personnellement, comme écrivain voyageur, j’ai découvert la liberté en pouvant donner plus « de moi-même », dans des tâches comme professeur volontaire de langues dans des communautés amérindiennes misaks de Colombie, les quichuas d’Équateur, du Pérou, les guaranis du Paraguay, au Venezuela, les gosses indigènes de l’Amazonie au Guyana, a Boa Vista au nord du Brésil, en aidant les frères franciscains de Rio de Janeiro ainsi qu’au Panama, dans les communautés du café du volcan Barú.",
   "page_us_p16_about"=>"Si j’étudie et enseigne la musique baroque, appelée aussi musique sacrée, c’est que le piano classique est devenu le vecteur essentiel de ma relation étroite avec le Père Céleste. Elle est pour moi, la forme transcendantale vers le Créateur.",
   "page_us_p17_about"=>"En ayant étudié, sans les approfondir, les techniques orientales de médecine, j’ai pu comprendre que la manière de s’alimenter joue un grand rôle dans le comportement de l’être humain.",
   "page_us_p18_about"=>"You are what you eat",
   "page_us_p19_about"=>"…Vous êtes ce que vous mangez, un dicton bien connu d’un philosophe grec. J’ajouterai : selon ce que vous mangez, et la manière sobre de s’alimenter, comme dans le régime macrobiotique ou végétalien, construit en vous un espace de paix. Toute chose sur terre et dans l’univers existe en opposition complémentaire. En vivant dans un monde baignant dans l’extrême acidité (alimentation dégradée, vulgarité, égoïsme, contamination acoustique, pollution de l’air, de l’eau et de l’esprit), il est nécessaire d’équilibrer en se nourrissant de céréales, de plantes, de fruits, que je nommerai : régime alcalin. Je conseille une alimentation à 80% alcaline (YIN) et 20% acide (YANG). On reconnaîtra plus facilement les êtres humains végétariens dans leur manière de vivre non agressive et la relation avec autrui.",
   "page_us_p20_about"=>"Dans notre monde, le symbole ne reste-t-il pas la croix? L’homme tiraillé entre une force ascensionnelle, l’appel de Dieu à partager l’amour et une force qui le tire vers le bas, le chemin de la servitude de sa soi-disant liberté. Ainsi qu’un équilibre entre le YIN et le YANG, altération entre l’alcalin et l’acide.",

    //Write
   "page_home_title_p3_write"=>"III. Raisons d'etudier la musique ancienne au piano",
   "page_home_date_p3_write"=>"27 Avril 2016",
   "page_home_body_p3_write"=>"Pourquoi étudier au piano, des œuvres écrites par des compositeurs baroques, tellement vieux, à cheval entre la Renaissance et le Classique. L’équilibre harmonique. Pour les débutants, en majorité les enfants : il vous oblige à faire fonctionner les deux parties du cerveau. La partie gauche du cerveau correspond à la logique, il traitera l’aspect fonctionnel, mathématique de la musique, comme le découpage des sons en blanches, noires, croches, demi croches etc… La partie droite du cerveau traitera de l’art, la mélodie, le chant ! Car n’oublions pas que jouer au piano est simplement faire chanter son instrument ! En arrivant à coordonner les deux mains, on atteindra à l’harmonie. Il s’agit presque d’une lutte entre la tête (main gauche) et le cœur (main droite) entre l’expansion mélodique et la tension rythmique, entre la structure et la rêverie. Le plus intéressant est le renversement, passant la mélodie à la main gauche et le rythme à la droite…",
   "page_home_title_p4_write"=>"IV. Musicotherapie et psychologie",
   "page_home_date_p4_write"=>"27 Avril 2016",
   "page_home_body_p4_write"=>"Ces informations nous ont été fournies par des journaux aux Etats-Unis. Une demi-heure de musique classique par jour : c’est obligatoire pour tous les enfants de Floride, aux Etats-Unis. Surnommée Beethoven’s Babies Bill, la loi 660 n’a pas pour seul objectif d’aider les petits à s’endormir à l’heure de la sieste, elle vise également à stimuler d’une façon harmonieuse leur développement cérébral… En France, l’action bénéfique de la musique n’est pas totalement inconnue. Dans les hôpitaux parisiens Armand-Trousseau et Necker, les salles de préanesthésie infantile deviennent de véritables salles de concert : enfants, parents et personnel soignant peuvent y manipuler des instruments, découvrir des sons, improviser ou écouter des cassettes. Après cette mise en condition, un musicien accompagne l’enfant jusque dans la salle d’opération en faisant résonner dans les dédales de couloirs, d’ascenseurs et autres lieux froids inconnus, des sons harmonieux et rassurants. Les résultats sont concluants puisque la musique joue un rôle positif sur la réussite des anesthésies et aide les enfants à mieux vivre le traumatisme de leur séjour hospitalier.",
   "page_home_title_p5_write"=>"V. Mon parcours comme enseignant",
   "page_home_date_p5_write"=>"27 Avril 2016",
   "page_home_body_p5_write"=>"Mon parcours, comme enseignant volontaire, dans les communautés amérindiennes. Dans le nord de l’Amérique, j’ai été fasciné par les Sioux, les Navajos, dans les grandes plaines, les Cheyennes du sud-est, les Apaches au sud-ouest. J’ai pu visiter les réserves, échanger des idées avec beaucoup d’entre eux. Ils y parlent autant de dialectes différents que la population entière amérindienne de Colombie. Contrairement aux voyageurs touristes en avion qui connaissent bien plus les capitales des pays qu’ils visitent, l’aéroport et les hôtels internationaux confortables étant proches ; personnellement, humble voyageur routier, sans horaire, sans contraintes, ne comprenant pas bien l’objectif des voyages organisés, je commençais doucement à me sentir envahis par cette douce sauvagerie primitive. Je me sentais plus proche des autochtones que de la majorité blanche de ces petits pays d’Amérique centrale. Avec eux, j’ai appris à vivre le plus simplement possible, en contact avec la nature et tâchant de goûter à tout, surtout au silence. Je n’aime pas parler de pauvreté ; mais vivre des produits frais de la terre, au rythme des saisons, de ses récoltes bonnes ou mauvaises. La dureté des conditions et des aléas du climat, vous donne l’envie de crier justice !",


   //footer
   "footer_text"=>"Nous avons besoin de votre soutien un don pour que ce projet continue d'exister.",
   "footer_button"=>"Soutenez-nous",
   "footer_copyright"=>"© Musica Dominus. 2022 Tous droits réservés."


];