<?php
return [

   //Header
   'page_home_title_what'=>"O que é Musica Dominus?",
   "nav_home"=>"Início",
   "nav_us"=>"Nós",
   "nav_write"=>"Meus escritos",
   "nav_gallery"=>"Galeria",
   "nav_contact"=>"Contato",
   "nav_don"=>"Doação",
   "nav_lang"=>"Idioma", 

   //banner
   "page_home_banner_p0"=>"Aventura",
   "page_home_banner_p1"=>"Inspiração",
   "page_home_banner_p2"=>"Paixões",
   "page_home_banner_p3"=>"Reconecte-se para ensinar valores verdadeiros.",
   "page_home_banner_p4"=>"CONTINUAR",

   //body Home what
   'page_home_title_what'=>"O que é Musica Dominus?",
   "page_home_subtitle_what"=>"O estudo da música clássica é a melhor forma, com a oração, de superar esses inconvenientes",
   "page_home_what_p1"=>"Em todas as instituições de ensino e em muitas comunidades, estamos testemunhando atos de ciúmes, assédio, intimidação. São as crianças mais sensíveis que muitas vezes são os alvos. Mesmo sofrendo essa violência verbal e psicológica quando criança. O estudo da música clássica é a melhor forma, com a oração, de poder ultrapassar estes inconvenientes, permitindo à criança equilibrar-se, encontrar o seu lugar no mundo, desenvolver-se com capacidade de afirmação. capítulos anteriores, os excessos de violência e vulgarização são os sinais de nossa sociedade decadente, materialista e egocêntrica.",
   "page_home_what_p2_b"=>"Música Dominus",
   "page_home_what_p2"=>"é uma forma de se reconectar com o ensino dos verdadeiros valores através do estudo da Bíblia, adequado para crianças de todas as idades, sobre o tema da música antiga. Dedico este ensino aos mais carentes, às crianças que não têm a chance de ter acesso a uma educação musical de qualidade, especialmente não a de um instrumento clássico como o pianoforte.",
   "page_home_what_p3"=>"Com intensa atenção e concentração, através da meditação, o estudo e interpretação de minuetos, sonatinas, árias por jovens iniciantes serão gravados e acessíveis em seu 'eu' mais profundo, sua verdadeira natureza finalmente revelada pela música antiga. presença do Espírito ao seu lado e o caminho para o sucesso, esse 'sentimento de conquista', essa é a iluminação de uma criança marginalizada por uma má orientação na escola, na comunidade ou simplesmente, vagando na rua.",

   //body Home gallery
   "page_home_title_gallery"=>"Galerias",
   "page_home_subtitle_gallery"=>"Eu capturei muitos dos momentos maravilhosos que vivi nesta bela aventura",
   "page_home_subtitle_what"=>"O estudo da música clássica é a melhor forma, com a oração, de superar esses inconvenientes",
   "page_home_more_gallery"=>"Ver mais álbum",

   //body home write
   "page_home_title_write"=>"Meus escritos",
   "page_home_subtitle_write"=>"As aventuras deste lindo projeto Musica Dominus me inspiraram a escrever e contar minhas experiências.",
   "page_home_title_p0_write"=>"Prólogo",
   "page_home_date_p0_write"=>"27 de abril de 2016",
   "page_home_body_p0_write"=>"Se a música é uma forma de oração, toda harmonia é uma forma de silêncio. Percebemos isso tão bem quando um barulho explode no fervor de uma noite de verão na Amazônia. Toda a natureza era vibrante, toda a vida ressoava na embriaguez carmesim da luz filtrada pelas copas das árvores. Os raios de luz que os atravessavam, celebravam em antífonas ardentes o êxtase do sol... , um argumento, um grito de amor nos revelou a majestade do silêncio.",
   "page_home_title_p1_write"=>"I.Introdução",
   "page_home_date_p1_write"=>"27 de abril de 2016",
   "page_home_body_p1_write"=>"Viajar não é uma reação de revolta do mundo, mas mais a necessidade de respirar! Parece até que uma viagem não é decidida imediatamente ou melhor, não é programada! Desdobramos nosso roteiro, o de toda a América, o coração dispara, a decisão e até a direção, parece ser tomada muitas vezes antes de encontrar o verdadeiro motivo. Na época, nos anos 80, desembarquei na costa oeste dos Estados Unidos, cheio de ambição. Antes, eu levava uma vida muito agradável, morando em um pequeno veleiro de 25 pés no porto de Antibes, no sul da França. Assim que o mistral começou a soprar, varrendo fortemente as nuvens cinzentas e o swell que vinha até nós do Golfo de Gênova, pegamos minha namorada e eu, o leme em direção a Saint-Tropez ou às ilhas de Hyères. Para ganhar a vida, tínhamos um pequeno restaurante bem modesto.",
   "page_home_title_p2_write"=>"I. Significado Espiritual da Musica Dominus",
   "page_home_date_p2_write"=>"27 de abril de 2016",
   "page_home_body_p2_write"=>"Se recebi uma educação católica tradicional, admito que não tive uma convicção muito profunda na minha juventude. Respeitava e seguia essa religião ensinada pela minha família. Minha avó era musicista, ela me levou aos concursos da Rainha Elisabeth em Bruxelas. Fiquei maravilhado com os concertos de piano de Ludwig von Beethoven interpretados por Emil Gilels, os nocturnos e Polonaises de Frederic Chopin interpretados por Mauricio Polini e outros por Tchaikovsky, tocados com destaque por este pianista russo cujo nome esqueci. Tentei reproduzir esses sons extraordinários no piano preto da mansão do meu avô. Descobri os acordes que ressoavam graças aos tetos altos desta residência de pedra com suas colunas de mármore.",
   "page_home_more_write"=>"Saiba mais",

   //US
   "page_us_body_p0"=>"Em todas as instituições de ensino e em muitas comunidades, estamos testemunhando atos de ciúmes, assédio, intimidação. São as crianças mais sensíveis que muitas vezes são os alvos. Mesmo sofrendo essa violência verbal e psicológica quando criança. O estudo da música clássica é a melhor forma, com a oração, de poder ultrapassar estes inconvenientes, permitindo à criança equilibrar-se, encontrar o seu lugar no mundo, desenvolver-se com capacidade de afirmação. capítulos anteriores, os excessos de violência e vulgarização são os sinais de nossa sociedade decadente, materialista e egocêntrica.",
   "page_us_body_p1"=>"é uma forma de se reconectar com o ensino dos verdadeiros valores através do estudo da Bíblia, adequado para crianças de todas as idades, sobre o tema da música antiga. Dedico este ensino aos mais necessitados, às crianças que não têm a chance de ter acesso a uma educação musical de qualidade, especialmente não a de um instrumento clássico como o pianoforte.",
   "page_us_body_p2"=>"Com intensa atenção e concentração, através da meditação, o estudo e interpretação de minuetos, sonatinas, árias por jovens iniciantes serão gravados e acessíveis em seu 'eu' mais profundo, sua verdadeira natureza finalmente revelada pela música antiga. presença do Espírito ao seu lado e o caminho para o sucesso, esse 'sentimento de conquista', essa é a iluminação de uma criança marginalizada por uma má orientação na escola, na comunidade ou simplesmente, vagando na rua.",
   "page_us_body_p3"=>"Quis terminar especificando que o piano, o rei dos instrumentos, reúne em si mesmo, em harmonia, os instrumentos usados ​​pelo rei Davi e sua corte durante as orações dos salmos. Na liturgia judaica do Templo, a cadência comandada pelos instrumentos parecia ter mais lugar do que a melodia. A música servia sobretudo para dar ritmo aos vários movimentos da celebração com o tambor ou o pandeiro e os címbalos. chifre, feito com chifre de bode, servindo para anunciar a presença do Senhor, misturando-se harmoniosamente com a lira, tocada por Davi.",
   "page_us_body_p4"=>"Todos os povos batam palmas! Deus sobe em aclamação, Javé ao som da buzina! Salmo (47) 46, 1 - 6",
   "page_us_body_p5"=>"O piano acústico moderno é um instrumento de cordas percutidas, a tábua harmônica deve ser da melhor qualidade de madeira. O metrônomo, marcando a cadência, é essencial e os três pedais permitem que o jovem músico aprenda a 'expressar , sem excessos, do piano ao forte através da concentração, meditação e estudo diário.",
   "page_us_body_p6"=>"Por favor, ajude-nos a espalhar a mensagem.",
   "page_us_body_p7"=>"Suas doações são bem-vindas e serão investidas neste objetivo.",

   "page_us_title_about"=>"Sobre mim",
   "page_us_subtitle_about"=>"Não há amor a ser tomado, há amor a ser recebido. Há tanto amor a ser recebido quanto há a ser dado e o que o cristianismo faz, é que tudo pode ser experimentado na forma de receber e dar.",
   "page_us_p00_about"=>"Olá, antes de mais nada, gostaria de me apresentar:",
   "page_us_p0_about"=>"Vincent Cambier",
   "page_us_p1_about"=>"nasceu em 10 de dezembro de 1057, em Ronse, uma pequena cidade do reino da Bélgica, localizada a poucos quilômetros da fronteira francesa, sendo as cidades de Roubaix, Tourcoing e Lille as mais próximas. Educação católica tradicional, grega latim no colégio jesuíta.",
   "page_us_p2_about"=>"A partícula 'de La Lozerie' vem de nossas origens, quando fomos nomeados cavaleiros no século 14. Eu a uso em todos os meus livros de aventura de viagem, não por esnobismo ou pretensão, só que é mais bonito e o nome Cambier é muito difícil de pronunciar na América.",
   "page_us_p3_about"=>"Juventude musical graças à minha avó materna: Lutgarde, originária de Tongres, em Limburg, perto da fronteira alemã.",
   "page_us_p4_about"=>"Aos 20 anos, parti da Europa para San Diego, Califórnia, nos Estados Unidos, com Béatrice, a jovem e bonita garçonete do restaurante que havíamos criado em Antibes, no sul da França. o resto da minha juventude foi profundamente influenciado pela cultura norte-americana dos anos 80: culto ao corpo, beleza plástica e vida materialista. Rapidamente me tornei o melhor vendedor de uma agência de casamentos, na época em que os computadores não existiam Dirigi um Cadillac e viajei entre Newport Beach, Hollywood, Beverly Hills e La Jolla, a joia da Califórnia, um balneário ao norte de San Diego onde tinha meu veleiro, um saveiro de 30 pés, no porto de Mission Bay. ",
   "page_us_p5_about"=>"A Jeannot de 25 pés, ancorada no porto de Vauban de Antibes onde dormíamos, Béatrice e eu, embalados pelas ondas do Mediterrâneo já estávamos longe, assim como ela, a quem abandonei, preferindo belezas plásticas de jovens americanos.",
   "page_us_p6_about"=>"Aos 40 anos, fui jornalista, escritor e até vendedor de uma revista de vinhos e gastronomia em Cannes, nos Alpes Marítimos, na França. Alguns anos depois, fui convidado pela companhia aérea nacional de Chile, bem como por alguns grandes comerciantes produtores de vinhos desta região do novo mundo. Instalado confortavelmente na luxuosa suíte do último andar do hotel Crowne Plaza em Santiago do Chile, onde joguei bilhar com o chef suíço, pude para provar a cozinha exótica, maravilhada com as jovens latinas de tez dourada do bairro de Bella Vista, o bairro boêmio da capital. Após esta reportagem sobre vinhos do novo mundo, voltei à Califórnia, convidado pela associação Napa e Sonoma Vinhos do Vale.",
   "page_us_p7_about"=>"Mais tarde, me estabeleci no estado do Arizona, nos Estados Unidos, onde criei minha própria linha de fragrâncias e cosméticos para casa: 'La Lozerie en Provence', fabricada pela família Grangeon estabelecida em St Rémy de Provence. Estes foram os melhores anos: dez anos de trabalho sem tirar férias, divididos entre o sul da França e toda a América do Norte. A bordo do Dodge RAM e seu inesquecível motor V8 de 5 litros, que rebocou sem esforço um Pace de 10 x 6 pés Reboque americano, que serviu tanto de escritório quanto de ancoradouro. Nova Inglaterra, Geórgia, Texas, Centro-Oeste, Chicago e Illinois, Michigan, Colorado e Utah, a fronteira canadense, Seattle e Vancouver, toda a Califórnia que eu conhecia bem, Arizona e Louisiana, onde pude falar francês com os últimos negros americanos de Nova Orleans, La Fayette e t Bâton Rouge, amigos afro-americanos que preservaram os verdadeiros valores do passado e a cultura de seus ancestrais.",
   "page_us_p8_about"=>"A crise econômica de 2018 e 2019, a queda dos dois maiores bancos e o crédito hipotecário nos Estados Unidos marcaram o fim do sonho americano, que havia sido criado pela era Clinton e sua miragem financeira. Em poucas semanas, perdi um terço dos meus clientes que não conseguiam mais honrar as faturas de seus pedidos feitos na 'La Lozerie en Provence' que perdeu pouco mais de cem mil dólares. sistema que estava matando pequenos empresários, agora os figurões das multinacionais , decidi cruzar a fronteira para o México, enviando os cheques sem fundos, 'cheques sem fundos' e faturas não pagas voando pela janela aberta do Dodge. Tanto pior para a ecologia.",
   "page_us_p10_about"=>"De San Diego, EUA a São Francisco, Brasil:",
   "page_us_p11_about"=>"Durante essas viagens, enfrentei tantas dificuldades: lâminas de mola quebradas, duas rodas perdidas, rolando sozinho! Na imensidão da grande savana venezuelana, guarda-lamas rasgados e esmagados por choques, pneus estourados, junta do cabeçote que fritou duas vezes dois motores: o motor Ram original da Dodge Chrysler, um MWM turbo diesel instalado no Paraguai, correias desfiadas… na véspera de Natal do estacionamento da paróquia de San Felix, no centro da Venezuela, os controles da polícia militar do Brasil e da corrupta Guarda Nacional da Venezuela, as paradas de “controle” dos paramilitares de El Salvador, as estradas sem barreiras de segurança cruzando e com vista para o Pacífico no Peru, as manifestações dos anos 2009 em Honduras... as estradas articuladas pessoas do México... e as crianças que mendigam porque estão com fome. kes a força de um viajante é essa vontade interior que sempre o impulsiona a seguir em frente, ir mais longe.",
   "page_us_p12_about"=>"Esses anos de viagens aventureiras me ensinaram que em San Diego, Califórnia, eu não era um homem livre. Eu era um escravo da minha vida materialista e egoísta. Cada vez mais bonita. Agora que perdi minha vida terrena Pai, eu sei que nosso Pai espiritual, o Criador de todo este universo, não criou a liberdade para nós, pois criou o Homem com a liberdade de se libertar. A verdadeira liberdade não se encontra nas praias do Panamá ou da Costa Rica, nem na grande savana, nos braços de uma bela venezuelana. A liberdade só é liberdade se a criarmos, pois a voz da natureza ressoa constantemente no homem um chamado a viver não para Deus e para os outros homens, mas apenas para si mesmo, egoisticamente, como os outros seres da natureza que vivem de acordo com seu instinto. documentando-me e lendo os livros espirituais de meu pai, escritos por François Varillon e Maurice Zundel, entendi que há no homem (e na mulher) uma força dupla: por um mão, uma força de gravidade e inércia que em convida-o a desistir de ser um homem livre e o impele a viver como os outros seres do mundo que não têm liberdade para construir. E, por outro lado, uma força ascendente que o convida a construir sua liberdade que Deus, pela graça, dará acesso à sua própria liberdade. A verdadeira liberdade encontra-se na divindade, acolhendo Cristo no coração, vivendo segundo o seu exemplo, negando-se a si mesmo. Dois grandes exemplos de homens livres foram Francisco de Assis ou Carlos de Foucault, que levaram suas vidas compartilhando com os outros e vivendo para os outros. Tão poucos de nós, simples pecadores, podem atingir tal nível de santidade e divindade, é necessário que modifiquemos nosso comportamento em relação aos outros. Porque a essência do pecado é desencadear um trem de ondas que perturba as relações humanas. Toda má ação ou pensamento é uma provocação ao mal que depositamos na consciência dos outros.",
   "page_us_p13_about"=>"Não há amor para receber, enquanto há amor para receber. Há tanto amor para receber quanto para dar e o que faz o cristianismo, é que tudo pode ser vivido no modo de acolher e dar." ,
   "page_us_p14_about"=>"Para aqueles que têm dificuldade, para viver de acordo com esses preceitos em nossa vida cotidiana, nesta sociedade brutal, decadente e corrompida pelo vício e pelo egoísmo, a opção de viver em comunidade deve ser explorada.",
   "page_us_p15_about"=>"Pessoalmente, como escritor de viagens, descobri a liberdade ao poder dar mais 'de mim', em tarefas como professor voluntário de línguas nas comunidades ameríndias Misak da Colômbia, os Quichuas do Equador, do Peru, os Guarani do Paraguai, da Venezuela, os meninos indígenas da Amazônia na Guiana, em Boa Vista no norte do Brasil, ajudando os frades franciscanos no Rio de Janeiro e no Panamá, nas comunidades cafeeiras do vulcão Barú.",
   "page_us_p16_about"=>"Se estudo e ensino música barroca, também chamada de música sacra, é porque o piano clássico tornou-se o vetor essencial da minha estreita relação com o Pai Celestial. Para mim, é a forma transcendental do Criador .",
   "page_us_p17_about"=>"Ao estudar, sem aprofundá-las, as técnicas orientais da medicina, pude compreender que a forma de comer desempenha um grande papel no comportamento do ser humano.",
   "page_us_p18_about"=>"Você é o que você come",
   "page_us_p19_about"=>"…Você é o que você come, um conhecido ditado de um filósofo grego. Acrescento: de acordo com o que você come, e a forma sóbria de comer, como na dieta macrobiótica ou vegana, constrói um espaço de paz dentro de você. Tudo na terra e no universo existe em oposição complementar. Ao viver em um mundo banhado em extrema acidez (comida degradada, vulgaridade, egoísmo, contaminação acústica, poluição do ar, água e espírito), é necessário equilíbrio comendo cereais, plantas, frutas, que chamarei de: dieta alcalina. Recomendo uma dieta de 80% alcalina (YIN) e 20% ácida (YANG). O ser humano vegetariano será mais facilmente reconhecido em sua forma não agressiva da vida e sua relação com os outros.",
   "page_us_p20_about"=>"Em nosso mundo, o símbolo não permanece a cruz? O homem dividido entre uma força ascendente, o chamado de Deus para compartilhar o amor e uma força que o puxa para baixo, o caminho da escravidão de sua chamada liberdade. Assim como um equilíbrio entre YIN e YANG, alteração entre alcalino e ácido.",

   //Write
   "page_home_title_p3_write"=>"III. Razões para estudar música antiga ao piano",
   "page_home_date_p3_write"=>"27 de abril de 2016",
   "page_home_body_p3_write"=>"Por que estudar ao piano, obras escritas por compositores barrocos, tão antigos, abrangendo o Renascimento e o Clássico. Equilíbrio harmônico. Para iniciantes, principalmente crianças: obriga a fazer funcionar as duas partes do cérebro. A parte esquerda do cérebro corresponde à lógica, processará o aspecto funcional, matemático da música, como a divisão dos sons em meias notas, semínimas, colcheias, semicolcheias etc... A parte direita do cérebro vai lidar com arte, melodia, canto! Porque não esqueçamos que tocar piano é simplesmente fazer seu instrumento cantar! Conseguindo coordenar as duas mãos, alcançaremos a harmonia. É quase uma luta entre a cabeça (esquerda mão) e o coração (mão direita) entre expansão melódica e tensão rítmica, entre estrutura e devaneio. O mais interessante é a inversão, passando a melodia para a mão esquerda e o ritmo para a direita…",
   "page_home_title_p4_write"=>"IV. Musicoterapia e psicologia",
   "page_home_date_p4_write"=>"27 de abril de 2016",
   "page_home_body_p4_write"=>"Esta informação nos foi fornecida por jornais nos Estados Unidos. Meia hora de música clássica por dia é obrigatória para todas as crianças na Flórida, Estados Unidos. Apelidada de Beethoven's Babies Bill , a lei 660 não se destina apenas a ajudar as crianças a adormecer na hora da soneca, também visa estimular o desenvolvimento cerebral de forma harmoniosa... Na França, a ação benéfica da música não é completamente desconhecida. Nos hospitais parisienses Armand-Trousseau e Necker, o bebê pré- salas de anestesia tornam-se verdadeiras salas de concerto: crianças, pais e equipe de enfermagem podem manipular instrumentos, descobrir sons, improvisar ou ouvir cassetes locais, sons harmoniosos e tranquilizadores. Os resultados são conclusivos, pois a música desempenha um papel positivo no sucesso da anestesia e ajuda a criança a lidar melhor com o trauma a de sua permanência no hospital.",
   "page_home_title_p5_write"=>"V. Minha carreira como professor",
   "page_home_date_p5_write"=>"27 de abril de 2016",
   "page_home_body_p5_write"=>"Minha jornada como professor voluntário em comunidades nativas americanas. Na América do Norte, fiquei fascinado com os Sioux, os Navajos, nas Grandes Planícies, os Cheyennes do Sudeste, os Apaches no sudoeste. visite as reservas, troque ideias com muitos deles. Eles falam tantos dialetos diferentes quanto toda a população ameríndia da Colômbia. Ao contrário dos viajantes aéreos turísticos que conhecem muito mais as capitais dos países que visitam, o aeroporto e os confortáveis ​​hotéis internacionais estando perto; pessoalmente, humilde viajante, sem horários, sem constrangimentos, não entendendo bem o objetivo das viagens organizadas, aos poucos fui me sentindo invadido por essa suave selvageria primitiva. pequenos países da América Central. Com eles, aprendi a viver da forma mais simples possível, em harmonia com a natureza e tentando saborear tudo, principalmente o silêncio. ke falar sobre pobreza; mas vive dos produtos frescos da terra, ao ritmo das estações, das suas boas ou más colheitas. A dureza das condições e os caprichos do clima fazem você querer gritar justiça!", 
   
   //Footer
   "footer_text"=>"Precisamos do seu apoio uma doação para manter este projeto em andamento.",
   "footer_button"=>"Apoie-nos",
   "footer_copyright"=>"© Musica Dominus. 2022 Todos os direitos reservados.",

];