<?php
return [

   //Header
   "page_home_title_what"=>"Was ist Musica Dominus?",
   "nav_home"=>"Startseite",
   "nav_us"=>"Wir",
   "nav_write"=>"Meine Schriften",
   "nav_gallery"=>"Galerie",
   "nav_contact"=>"Kontakt",
   "nav_don"=>"Spende",
   "nav_lang"=>"Sprache",

   //banner
   "page_home_banner_p0"=>"Abenteuer",
   "page_home_banner_p1"=>"Inspiration",
   "page_home_banner_p2"=>"Leidenschaften",
   "page_home_banner_p3"=>"Verbinden Sie sich erneut, um wahre Werte zu lehren.",
   "page_home_banner_p4"=>"WEITER",

   //body Home what
   'page_home_title_what'=>"Was ist Musica Dominus?",
   "page_home_subtitle_what"=>"Das Studium der klassischen Musik ist der beste Weg, um diese Unannehmlichkeiten mit Gebet zu überwinden",
   "page_home_what_p1"=>"In allen Bildungseinrichtungen und in vielen Gemeinden werden wir Zeugen von Akten der Eifersucht, Belästigung, Einschüchterung. Es sind die sensibelsten Kinder, die sehr oft das Ziel sind. sogar als Kind unter dieser verbalen und psychischen Gewalt zu leiden. Das Studium der klassischen Musik ist der beste Weg, um diese Unannehmlichkeiten mit Gebet zu überwinden, indem es dem Kind ermöglicht, sich auszugleichen, seinen Platz in der Welt zu finden, sich zu entwickeln, indem es in der Lage ist, sich selbst zu behaupten vorangegangenen Kapiteln sind Gewaltexzesse und Vulgarisierung die Zeichen unserer dekadenten, materialistischen und egozentrischen Gesellschaft.",
   "page_home_what_p2_b"=>"Musica Dominus",
   "page_home_what_p2"=>"ist eine Möglichkeit, sich wieder mit der Lehre wahrer Werte durch das Studium der Bibel zu verbinden, die für Kinder jeden Alters zum Thema Alte Musik geeignet ist. Ich widme diese Lehre den am stärksten benachteiligten Kindern, die haben keine Chance auf eine qualitativ hochwertige musikalische Ausbildung, schon gar nicht auf einem klassischen Instrument wie dem Pianoforte.",
   "page_home_what_p3"=>"Mit intensiver Aufmerksamkeit und Konzentration wird durch Meditation das Studium und die Interpretation von Menuetten, Sonatinen und Arien von jungen Anfängern in ihr tiefstes 'Selbst' eingraviert und zugänglich gemacht, ihre wahre Natur schließlich durch Alte Musik offenbart. Dies Gegenwart des Geistes an ihrer Seite und der Weg zum Erfolg, dieses 'Erfolgsgefühl', das ist die Erleuchtung eines Kindes, das durch eine schlechte Orientierung in der Schule, in der Gemeinde oder einfach auf der Straße umherirrt.",

   //body Home gallery
   "page_home_title_gallery"=>"Galerien",
   "page_home_subtitle_gallery"=>"Ich habe viele der wunderbaren Momente festgehalten, die ich in diesem wunderschönen Abenteuer erlebt habe",
   "page_home_subtitle_what"=>"Das Studium der klassischen Musik ist der beste Weg, um diese Unannehmlichkeiten mit Gebet zu überwinden",
   "page_home_more_gallery"=>"Weiteres Album anzeigen",

   //body home write
   "page_home_title_write"=>"Meine Schriften",
   "page_home_subtitle_write"=>"Die Abenteuer dieses wunderschönen Projekts Musica Dominus haben mich dazu inspiriert, meine Erfahrungen zu schreiben und zu erzählen.",
   "page_home_title_p0_write"=>"Vorwort",
   "page_home_date_p0_write"=>"27. April 2016",
   "page_home_body_p0_write"=>"Wenn Musik eine Form des Gebets ist, ist alle Harmonie eine Form der Stille. Wir erkennen das so gut, wenn ein Geräusch in die Inbrunst eines Sommerabends im Amazonas hineinbricht. Die ganze Natur war vibrierend, alles Leben läutete im purpurnen Rausch des Lichts, das durch die Baumwipfel drang. Die Lichtstrahlen, die sie durchquerten, feierten in feurigen Antiphonen die Ekstase der Sonne ... Und plötzlich durchbrachen durchdringende Schreie, die der Affengeher, all diese Beschwörung , ein Streit, ein Liebesschrei offenbarte uns die Majestät der Stille.",
   "page_home_title_p1_write"=>"I.Einführung",
   "page_home_date_p1_write"=>"27. April 2016",
   "page_home_body_p1_write"=>"Reisen ist keine Reaktion der Revolte der Welt, sondern mehr das Bedürfnis zu atmen! Es scheint sogar, dass eine Reise nicht sofort entschieden oder besser gesagt nicht programmiert ist! Wir entfalten unsere Roadmap, die von ganz Amerika, die Herzrasen, die Entscheidung und sogar die Richtung scheinen sehr oft getroffen zu werden, bevor der wahre Grund gefunden wird. Damals, in den 80er Jahren, landete ich voller Ehrgeiz an der Westküste der Vereinigten Staaten. Davor führte ich ein sehr angenehmes Leben auf einem kleinen 25-Fuß-Segelboot im Hafen von Antibes in Südfrankreich. Sobald der Mistral zu blasen begann und die grauen Wolken und die Dünung, die vom Golf von Genua auf uns zukam, stark fegte, nahmen wir mit meiner Freundin und mir das Ruder in Richtung Saint-Tropez oder den Inseln von Hyères. Um unseren Lebensunterhalt zu verdienen, hatten wir ein sehr bescheidenes kleines Restaurant.",
   "page_home_title_p2_write"=>"II Spirituelle Bedeutung von Musica Dominus",
   "page_home_date_p2_write"=>"27. April 2016",
   "page_home_body_p2_write"=>"Wenn ich eine traditionelle katholische Erziehung erhalten habe, gebe ich zu, dass ich in meiner Jugend keine sehr tiefe Überzeugung hatte. Ich habe diese von meiner Familie gelehrte Religion respektiert und befolgt. Meine Großmutter war Musikerin, sie hat mich aufgenommen zu den Königin-Elisabeth-Wettbewerben in Brüssel, ich war begeistert von den Klavierkonzerten Ludwig von Beethovens, interpretiert von Emil Gilels, den Nocturnes und Polonaisen von Frédéric Chopin, interpretiert von Mauricio Polini, und anderen von Tschaikowsky, gespielt mit Nachdruck von diesem russischen Pianisten, dessen Name I habe ich vergessen. Ich habe versucht, diese außergewöhnlichen Klänge auf dem schwarzen Klavier der Villa meines Großvaters zu reproduzieren. Ich habe die Akkorde entdeckt, die dank der hohen Decken dieser Steinresidenz mit ihren Marmorsäulen mitschwingen.",
   "page_home_more_write"=>"Mehr erfahren",

   //US
   "page_us_body_p0"=>"In allen Bildungseinrichtungen und in vielen Gemeinden werden wir Zeuge von Akten der Eifersucht, Belästigung, Einschüchterung. Es sind die sensibelsten Kinder, die sehr oft das Ziel sind. sogar als Kind unter dieser verbalen und psychischen Gewalt zu leiden. Das Studium der klassischen Musik ist der beste Weg, um diese Unannehmlichkeiten mit Gebet zu überwinden, indem es dem Kind ermöglicht, sich auszugleichen, seinen Platz in der Welt zu finden, sich zu entwickeln, indem es in der Lage ist, sich selbst zu behaupten vorangegangenen Kapiteln sind Gewaltexzesse und Vulgarisierung die Zeichen unserer dekadenten, materialistischen und egozentrischen Gesellschaft.",
   "page_us_body_p1"=>"ist eine Möglichkeit, sich wieder mit der Lehre wahrer Werte durch das Studium der Bibel zu verbinden, die für Kinder jeden Alters zum Thema Alte Musik geeignet ist. Ich widme diese Lehre den am stärksten benachteiligten Kindern, die haben keine Chance auf eine qualitativ hochwertige musikalische Ausbildung, schon gar nicht auf einem klassischen Instrument wie dem Pianoforte.",
   "page_us_body_p2"=>"Mit intensiver Aufmerksamkeit und Konzentration wird durch Meditation das Studium und die Interpretation von Menuetten, Sonatinen und Arien von jungen Anfängern in ihr tiefstes 'Selbst' eingraviert und zugänglich gemacht, ihre wahre Natur schließlich durch Alte Musik offenbart. Dies Gegenwart des Geistes an ihrer Seite und der Weg zum Erfolg, dieses 'Erfolgsgefühl', das ist die Erleuchtung eines Kindes, das durch eine schlechte Orientierung in der Schule, in der Gemeinde oder einfach auf der Straße umherirrt.",
   "page_us_body_p3"=>"Abschließend möchte ich sagen, dass das Klavier, der König der Instrumente, die Instrumente, die König David und sein Hofstaat während der Psalmengebete verwenden, in sich harmonisch vereint. Erinnern wir uns daran in In der jüdischen Liturgie des Tempels schien der von den Instrumenten befohlene Rhythmus mehr Platz zu nehmen als die Melodie, die Musik diente vor allem dazu, die verschiedenen Bewegungen der Feier mit der Trommel oder dem Tamburin sowie den Becken zu rhythmisieren Horn, hergestellt aus einem Ziegenhorn, das dazu dient, die Gegenwart des Herrn anzukündigen, und sich harmonisch mit der von David gespielten Leier verbindet.",
   "page_us_body_p4"=>"Alle Völker klatscht in die Hände! Gott steigt auf im Jubel, Jahwe im Klang des Horns! Psalm (47) 46, 1 - 6",
   "page_us_body_p5"=>"Das moderne akustische Klavier ist ein angeschlagenes Saiteninstrument, die Harmonika muss von bester Holzqualität sein. Das Metronom, das die Kadenz anzeigt, ist unerlässlich, und die drei Pedale ermöglichen es dem jungen Musiker, sich auszudrücken , ohne Exzess, von piano bis forte durch Konzentration, Meditation und tägliches Studium.",
   "page_us_body_p6"=>"Bitte helfen Sie uns, die Botschaft zu verbreiten.",
   "page_us_body_p7"=>"Ihre Spenden sind willkommen und werden in dieses Ziel investiert.",
   
   "page_us_title_about"=>"Über mich",
   "page_us_subtitle_about"=>"Es gibt keine Liebe, die man nehmen muss, es gibt Liebe, die man empfangen muss. Es gibt genauso viel Liebe zu empfangen wie zu geben, und was das Christentum tut, ist, dass alles auf diese Weise erfahren werden kann Empfangen und Geben.",
   "page_us_p00_about"=>"Hallo, zuerst wollte ich mich vorstellen:",
   "page_us_p0_about"=>"Vincent Cambier",
   "page_us_p1_about"=>"geboren am 10. Dezember 1057 in Ronse, einer kleinen Stadt im Königreich Belgien, nur wenige Kilometer von der französischen Grenze entfernt, wobei die Städte Roubaix, Tourcoing und Lille am nächsten sind. Traditionelle katholische Erziehung, Griechisch Latein am Jesuitenkolleg.",
   "page_us_p2_about"=>"Das Teilchen 'de La Lozerie' stammt aus unseren Ursprüngen, als wir im 14. Jahrhundert zum Ritter geschlagen wurden. Ich verwende es in allen meinen Reiseabenteuerbüchern, nicht aus Snobismus oder Anmaßung, nur weil es hübscher ist Der Name Cambier ist in Amerika zu schwer auszusprechen.",
   "page_us_p3_about"=>"Musikalische Jugend dank meiner Großmutter mütterlicherseits: Lutgarde, ursprünglich aus Tongres, in Limburg, nahe der deutschen Grenze.",
   "page_us_p4_about"=>"Im Alter von 20 Jahren verließ ich Europa mit Béatrice, der jungen und hübschen Kellnerin des Restaurants, das wir in Antibes in Südfrankreich gegründet hatten, nach San Diego, Kalifornien, in die Vereinigten Staaten. den Rest meiner Jugend stark beeinflusst von der nordamerikanischen Kultur der 80er Jahre: Körperverehrung, plastische Schönheit und materialistisches Leben, wurde ich sehr schnell zum besten Verkäufer einer Heiratsagentur, als es noch keine Computer gab Ich fuhr einen Cadillac und reiste zwischen Newport Beach, Hollywood, Beverly Hills und La Jolla, dem Juwel Kaliforniens, einem Badeort nördlich von San Diego, wo ich mein Segelboot, eine 30-Fuß-Schaluppe, im Hafen von Mission Bay hatte. ",
   "page_us_p5_about"=>"Die 25-Fuß-Jeannot, die im Vauban-Hafen von Antibes vor Anker lag, wo wir, Béatrice und ich, eingelullt von den Wellen des Mittelmeers, schon weit weg waren, genau wie sie, die ich verlassen hatte und Plastikschönheiten vorzog junger Amerikaner.",
   "page_us_p6_about"=>"Im Alter von 40 Jahren war ich Journalist, Autor und sogar Verkäufer für ein Wein- und Gastronomiemagazin in Cannes, in den Alpes Maritimes in Frankreich. Ein paar Jahre später wurde ich von der nationalen Fluggesellschaft von eingeladen Chile sowie von einigen großen Weinhändlern, die Weine aus dieser Region der Neuen Welt herstellen, bequem untergebracht in der luxuriösen Suite im obersten Stockwerk des Crowne Plaza Hotels in Santiago de Chile, wo ich mit dem Schweizer Koch Billard spielte, konnte ich um die exotische Küche zu probieren, staunend über die jungen lateinamerikanischen Damen mit goldenem Teint aus dem Bella Vista-Viertel, dem Künstlerviertel der Hauptstadt. Nach diesem Bericht über Weine aus der neuen Welt kehrte ich nach Kalifornien zurück, eingeladen von der Vereinigung Napa und Sonoma Talweine.",
   "page_us_p7_about"=>"Später ließ ich mich im Bundesstaat Arizona in den Vereinigten Staaten nieder, wo ich meine eigene Linie von Raumdüften und -kosmetik kreierte: 'La Lozerie en Provence', hergestellt von der in St. Rémy de ansässigen Familie Grangeon Provence Das waren die besten Jahre: Zehn Jahre Arbeit ohne Urlaub, verteilt auf Südfrankreich und ganz Nordamerika An Bord des Dodge RAM und seines unvergesslichen 5-Liter-V8-Motors, der mühelos einen 10 x 6 Fuß Pace schleppte Amerikanischer Wohnwagen, der sowohl als Büro als auch als Liegeplatz diente, Neuengland, Georgia, Texas, der Mittlere Westen, Chicago und Illinois, Michigan, Colorado und Utah, die kanadische Grenze, Seattle und Vancouver, ganz Kalifornien, das ich gut kannte, Arizona und Louisiana, wo ich Französisch mit den letzten schwarzen Amerikanern aus New Orleans, La Fayette und t Bâton Rouge sprechen konnte, afroamerikanische Freunde, die die wahren Werte der Vergangenheit und die Kultur ihrer Vorfahren bewahrt haben.",
   "page_us_p8_about"=>"Die Wirtschaftskrise 2018 und 2019, der Fall der beiden größten Banken und Hypothekenkredite in den Vereinigten Staaten markierten das Ende des amerikanischen Traums, der durch die Clinton-Ära und ihre finanzielle Fata Morgana geschaffen worden war Innerhalb weniger Wochen habe ich ein Drittel meiner Kunden verloren, die die Rechnungen für ihre Bestellungen bei 'La Lozerie en Provence', die etwas mehr als hunderttausend Dollar verloren hat, nicht mehr bezahlen konnten , beschloss ich, die Grenze nach Mexiko zu überqueren, und ließ die geplatzten Schecks, ungedeckten Schecks und unbezahlten Rechnungen aus dem offenen Fenster des Dodge fliegen. Umso schlimmer für die Ökologie.",
   "page_us_p9_about"=>"In ein paar Monaten, seit Nogales in Mexiko, werde ich zehn Grenzen überschritten haben: Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Kolumbien, Ecuador, Peru, Chile oder der V8-Motor in der Atacama-Wüste überhitzt, in Paraguay von einem argentinischen Mechaniker repariert, konnte ich eine scheinbar nie enden wollende Reise fortsetzen, quer durch Brasilien, Französisch Guyana, Suriname, Guyana, Boa Vista: das Tor zum Amazonas, Nordbrasilien , mitten in einer Wirtschaftskrise Venezuela durchquerend, erreichte ich mit großen Schwierigkeiten Cucuta, in Kolumbien auf der anderen Seite!Eine dritte Reise brachte mich dazu, Ayacucho, Arequipa in Peru, Bolivien der indianischen Kultur, den Titicaca-See, Jujuy in Argentinien zu entdecken , Tilcara, San Juan, die Grenzstraße der Anden: El Paso de Jama, Antofagasta, Arica in Chile, Chungara-See, San Pedro und das Azapa-Tal, wo peruanische Mechaniker das neue Wohnmobil aus den USA montieren konnten, während der zwei Jahre der Pandemie, wenn die Grenzen wurden geschlossen. Dank der Gastfreundschaft von Niksa Bezmalinovic, einem der letzten Bauern in diesem Wüstental, in dem ich in dem einfachen Wohnwagen leben konnte, der diesen Wüstenolivenhain auch für seine vollständige Renovierung ausgewählt hatte. So entstand das Reisemobil, das Sie auf dem Foto sehen: ein Ford-Truck aus Valparaiso, mit gemischter Zulassung aus Chile und Arizona, USA, wo es hergestellt wurde.",
   "page_us_p10_about"=>"Von San Diego, USA nach Sao Francisco, Brasilien:",
   "page_us_p11_about"=>"Während dieser Reisen habe ich so viele Schwierigkeiten durchgemacht: gebrochene Federblätter, zwei verlorene Räder, alleine rollen! In der Weite der großen venezolanischen Savanne, durch Stöße aufgerissene und zerschmetterte Kotflügel, geplatzte Reifen, Zylinderkopfdichtung der zweimal zwei Motoren gebraten hat: den originalen Ram-Motor von Dodge Chrysler, einen in Paraguay installierten MWM-Turbodiesel, zerfetzte Riemen… Die schlimmsten Momente waren der Bruch auf dem Feldweg zwischen dem Amazonas von Guyana und Brasilien, die vier Räder des gestohlenen Anhängers An Heiligabend vom Parkplatz der Pfarrei San Felix, im Zentrum Venezuelas, kontrollieren die Militärpolizei Brasiliens und die korrupte Guarda Nacional Venezuelas, die „Kontrolle“ der Paramilitärs von El Salvador, die Straßen ohne Sicherheitsbarrieren, die sich kreuz und quer über den Pazifik in Peru ziehen, die Demonstrationen der 2009er in Honduras … die schiefen Straßen der Menschen aus Mexiko … und die Kinder, die betteln, weil sie hungrig sind Was die Stärke eines Reisenden ausmacht, ist dieser innere Wille, der einen immer antreibt, vorwärts zu gehen, weiter zu gehen.",
   "page_us_p12_about"=>"Diese Jahre abenteuerlicher Reisen haben mich gelehrt, dass ich in San Diego, Kalifornien, kein freier Mann war. Ich war ein Sklave meines materialistischen, egoistischen Lebens. Ich wurde immer schöner. Jetzt, wo ich mein Irdisches verloren habe Vater, ich weiß, dass unser spiritueller Vater, der Schöpfer dieses ganzen Universums, die Freiheit nicht für uns geschaffen hat, denn er hat den Menschen mit der Freiheit erschaffen, sich selbst zu befreien. Wahre Freiheit findet man nicht an den Stränden von Panama oder Costa Rica, noch in der großen Savanne, in den Armen einer hübschen Venezolanerin. Freiheit ist nur dann Freiheit, wenn wir sie schaffen, denn die Stimme der Natur ertönt ständig im Menschen ein Ruf, nicht für Gott und für andere Menschen zu leben, sondern für sich allein, selbstsüchtig, wie die anderen Wesen der Natur, die nach ihrem Instinkt leben Als ich mich selbst dokumentierte und die spirituellen Bücher meines Vaters las, die von François Varillon und Maurice Zundel geschrieben wurden, verstand ich, dass es im Mann (und in der Frau) eine doppelte Kraft gibt: auf der einen andererseits eine Schwerkraft und Trägheit, die in lädt ihn ein, aufzugeben, ein freier Mann zu sein, und drängt ihn, wie die anderen Wesen der Welt zu leben, die keine Freiheit zum Bauen haben. Und andererseits eine nach oben gerichtete Kraft, die ihn einlädt, seine Freiheit aufzubauen, damit Gott ihm durch Gnade Zugang zu seiner eigenen Freiheit verschaffen wird. Wahre Freiheit findet man in der Göttlichkeit, indem man Christus in sein Herz aufnimmt, indem man nach seinem Beispiel lebt, indem man sich selbst verleugnet. Zwei großartige Beispiele für freie Männer waren Franz von Assisi oder Charles de Foucault, die ihr Leben durch das Teilen mit anderen und das Leben für andere führten. So wenige von uns einfachen Sündern können ein solches Maß an Heiligkeit und Göttlichkeit erreichen, dass wir unser Verhalten gegenüber anderen ändern müssen. Denn das Wesen der Sünde besteht darin, einen Wellenzug auszulösen, der die menschlichen Beziehungen zerstört. Jede schlechte Tat oder jeder schlechte Gedanke ist eine Provokation des Bösen, das wir im Gewissen anderer hinterlassen.",
   "page_us_p13_about"=>"Es gibt keine Liebe zu nehmen, während es Liebe zu empfangen gibt. Es gibt genauso viel Liebe zu empfangen wie zu geben, und was das Christentum ausmacht, ist, dass alles in der Art und Weise des Annehmens und Gebens gelebt werden kann." ,
   "page_us_p14_about"=>"Für diejenigen, die Schwierigkeiten haben, nach diesen Vorschriften in unserem Alltag zu leben, dieser brutalen Gesellschaft, dekadent und korrumpiert von Laster und Egoismus, ist die Möglichkeit zu erkunden, in Gemeinschaft zu leben.",
   "page_us_p15_about"=>"Persönlich habe ich als Reiseschriftsteller die Freiheit entdeckt, indem ich mehr 'von mir selbst' geben konnte, bei Aufgaben als ehrenamtlicher Sprachlehrer in den Misak-Indianergemeinschaften Kolumbiens, den Quichuas Ecuadors, aus Peru, die Guarani aus Paraguay, aus Venezuela, die indigenen Kinder vom Amazonas in Guyana, bei Boa Vista in Nordbrasilien, die Hilfe der Franziskanermönche in Rio de Janeiro sowie in Panama, in den Kaffeegemeinschaften des Barú-Vulkans.",
   "page_us_p16_about"=>"Wenn ich Barockmusik, auch Kirchenmusik genannt, studiere und unterrichte, dann deshalb, weil das klassische Klavier zum wesentlichen Träger meiner engen Beziehung zum himmlischen Vater geworden ist. Für mich ist es die transzendentale Form zum Schöpfer .",
   "page_us_p17_about"=>"Indem ich die orientalischen Techniken der Medizin studiert habe, ohne sie zu vertiefen, konnte ich verstehen, dass die Art zu essen eine große Rolle im Verhalten des Menschen spielt.",
   "page_us_p18_about"=>"Du bist, was du isst",
   "page_us_p19_about"=>"…Du bist, was du isst, ein bekannter Ausspruch eines griechischen Philosophen. Ich füge hinzu: Je nachdem, was du isst, baut auch die nüchterne Art der Ernährung, wie bei der makrobiotischen oder veganen Ernährung, auf Raum des Friedens in dir. Alles auf der Erde und im Universum existiert in komplementären Gegensätzen. Durch das Leben in einer Welt, die in extreme Säure gebadet ist (verdorbene Nahrung, Vulgarität, Egoismus, akustische Verschmutzung, Luftverschmutzung, Wasser und Geist), ist es notwendig Gleichgewicht durch den Verzehr von Getreide, Pflanzen, Früchten, die ich nennen werde: basische Ernährung Ich empfehle eine Ernährung mit 80 % basischem (YIN) und 20 % saurem (YANG) Vegetarier werden leichter in ihrer nicht aggressiven Art erkannt des Lebens und ihre Beziehung zu anderen.",
   "page_us_p20_about"=>"Bleibt das Symbol in unserer Welt nicht das Kreuz? Der Mensch ist hin- und hergerissen zwischen einer aufsteigenden Kraft, Gottes Ruf, Liebe zu teilen, und einer Kraft, die ihn nach unten zieht, dem Pfad der Knechtschaft seiner sogenannten Freiheit. Sowie ein Gleichgewicht zwischen YIN und YANG, Wechsel zwischen basisch und sauer.",

    //Write
   "page_home_title_p3_write"=>"III. Gründe, Alte Musik am Klavier zu studieren",
   "page_home_date_p3_write"=>"27. April 2016",
   "page_home_body_p3_write"=>"Warum am Klavier lernen, Werke von so alten Barockkomponisten zwischen Renaissance und Klassik. Harmonisches Gleichgewicht. Für Anfänger, meist Kinder: Es zwingt Sie, die beiden Teile des Gehirns zu funktionieren. Der linke Teil des Gehirns entspricht der Logik, er verarbeitet die funktionalen, mathematischen Aspekte der Musik, wie die Aufteilung von Tönen in halbe Noten, Viertelnoten, Achtelnoten, halbe Achtelnoten usw. Der rechte Teil des Gehirns wird sich mit Kunst, Melodie, Gesang befassen! Denn vergessen wir nicht, dass Klavierspielen einfach Ihr Instrument zum Singen bringt! Indem wir es schaffen, die beiden Hände zu koordinieren, erreichen wir Harmonie. Es ist fast eine Frage des Kampfes zwischen dem Kopf (links Hand) und das Herz (rechte Hand) zwischen melodischer Ausdehnung und rhythmischer Spannung, zwischen Struktur und Träumerei. Am interessantesten ist die Umkehrung, die Melodie in die linke Hand und den Rhythmus in die rechte Hand zu geben …",
   "page_home_title_p4_write"=>"IV. Musiktherapie und Psychologie",
   "page_home_date_p4_write"=>"27. April 2016",
   "page_home_body_p4_write"=>"Diese Information wurde uns von Zeitungen in den Vereinigten Staaten zur Verfügung gestellt. Eine halbe Stunde klassische Musik am Tag ist für alle Kinder in Florida, USA, obligatorisch. Das Gesetz 660 mit dem Spitznamen Beethoven's Babies Bill ist nicht nur dafür gedacht Kindern beim Einschlafen zu helfen, soll auch ihre Gehirnentwicklung auf harmonische Weise stimulieren... In Frankreich ist die wohltuende Wirkung von Musik nicht ganz unbekannt. In den Pariser Krankenhäusern Armand-Trousseau und Necker wird der Anästhesieräume werden zu echten Konzertsälen: Kinder, Eltern und Pflegepersonal können Instrumente manipulieren, Klänge entdecken, improvisieren oder Kassetten hören. Nach dieser Konditionierung begleitet ein Musiker das Kind in den Operationssaal, indem er im Labyrinth aus Gängen, Aufzügen und anderer unbekannter Kälte mitschwingt Orte, harmonische und beruhigende Klänge Die Ergebnisse sind überzeugend, da Musik eine positive Rolle für den Narkoseerfolg spielt und Kindern hilft, den Trauma besser zu bewältigen a ihres Krankenhausaufenthalts.",
   "page_home_title_p5_write"=>"V. Mein Werdegang als Lehrer",
   "page_home_date_p5_write"=>"27. April 2016",
   "page_home_body_p5_write"=>"Mein Weg als ehrenamtlicher Lehrer in indianischen Gemeinschaften. In Nordamerika war ich fasziniert von den Sioux, den Navajos, in den Great Plains, den südöstlichen Cheyenne, den Apachen im Südwesten. Ich konnte Besuchen Sie die Reservate, tauschen Sie sich mit vielen aus, sie sprechen dort so viele verschiedene Dialekte wie die gesamte indianische Bevölkerung Kolumbiens, im Gegensatz zu den touristischen Flugreisenden, die die Hauptstädte der besuchten Länder, den Flughafen und die komfortablen internationalen Hotels viel besser kennen Ich persönlich, bescheidener Straßenreisender, ohne Zeitplan, ohne Zwänge, der das Ziel der organisierten Reisen nicht gut verstand, begann mich langsam von dieser sanften primitiven Wildheit überfallen zu fühlen. Ich fühlte mich den Eingeborenen näher als der weißen Mehrheit von ihnen kleinen mittelamerikanischen Ländern, bei denen ich gelernt habe, so einfach wie möglich zu leben, im Einklang mit der Natur und zu versuchen, alles zu schmecken, besonders die Stille ke über Armut sprechen; sondern lebe von den frischen Produkten des Landes, im Rhythmus der Jahreszeiten, von seinen guten oder schlechten Ernten. Die Härte der Bedingungen und die Launen des Klimas machen Lust, Gerechtigkeit zu schreien!",

   //footer
   "footer_text"=>"Wir brauchen Ihre Unterstützung, eine Spende, um dieses Projekt am Laufen zu halten.",
   "footer_button"=>"Unterstütze uns",
   "footer_copyright"=>"© Musica Dominus. 2022 Alle Rechte vorbehalten.", 
   
];