<?php
return [
   //Header
   'nav_home'=>"Inicio", 
   "nav_us"=>"Nosotros",
   "nav_write"=>"Mis escritos",
   "nav_gallery"=>"Galería",
   "nav_contact"=>"Contacto",
   "nav_don"=>"Donación",
   "nav_lang"=>"Idioma",
   
   //banner
   "page_home_banner_p0"=>"Aventura",
   "page_home_banner_p1"=>"Inspiración",
   "page_home_banner_p2"=>"Pasión",
   "page_home_banner_p3"=>"Reconectando la enseñanza a los verdaderos valores.",
   "page_home_banner_p4"=>"CONTINUE",

   //body Home what
   'page_home_title_what'=>"¿Qué es Musica Dominus?",
   "page_home_subtitle_what"=>"El estudio de la música clásica es la mejor manera, con la oración, de poder superar estos inconvenientes",
   "page_home_what_p1"=>"En todas las instituciones educativas y en muchas comunidades estamos presenciando actos de celos, acoso e intimidación. Los niños más sensibles son a menudo los objetivos. Yo mismo sufrí esta violencia verbal y psicológica cuando era niño. El estudio de la música clásica es la mejor manera, con la oración, de poder superar estos inconvenientes permitiendo al niño equilibrarse, encontrar su lugar en el mundo, desarrollarse pudiendo afirmarse. Como hemos visto en capítulos anteriores, la violencia excesiva y la vulgarización son los signos de nuestra sociedad decadente, materialista y egocéntrica.",
   "page_home_what_p2_b"=>"Musica Dominus",
   "page_home_what_p2"=>"es una forma de reconectar con la enseñanza de los verdaderos valores a través del estudio de la Biblia, apta para niños de todas las edades, sobre el tema de la música antigua. Esta enseñanza la dedico a los más pobres, a los niños que no tienen la posibilidad de acceder a una educación musical de calidad, y mucho menos la de un instrumento clásico como el pianoforte.",
   "page_home_what_p3"=>"Con intensa atención y concentración, gracias a la meditación, el estudio y la interpretación de minuetos, sonatinas, arias por parte de jóvenes principiantes quedará grabado y accesible en su 'yo' más profundo, su verdadera naturaleza finalmente revelada por la música antigua. Esta presencia del Espíritu a su lado y camino al éxito, este “sentimiento de logro”, es la iluminación de un niño apartado por una mala orientación en la escuela, en la comunidad o simplemente deambulando por las calles.",
   
   //body Home gallery
   "page_home_title_gallery"=>"Galerías",
   "page_home_subtitle_gallery"=>"He capturado gran parte de los momentos maravillosos que he vivenciado en esta hermosa aventura",
   "page_home_more_gallery"=>"Ver más Galerías",
   
   //body home write 
   "page_home_title_write"=>"Mis Escritos",
   "page_home_subtitle_write"=>"Las Aventuras de este hermoso proyecto Musica Dominus, me ha inspirado a escribir y narrar experiencias y vivencias.",
   "page_home_title_p0_write"=>"Prefacio (Avant-Propos)",
   "page_home_date_p0_write"=>"27 Avril 2016",
   "page_home_body_p0_write"=>" Si la música es una forma de oración, toda armonía es una forma de silencio. Nos damos cuenta muy bien cuando un ruido estalla en el fervor de una tarde de verano en el Amazonas. Toda la naturaleza era vibrante, toda la vida resonaba en la intoxicación púrpura de la luz filtrada a través de las copas de los árboles. Los rayos de luz que los atravesaban, celebraban en antífonas de fuego el éxtasis del sol... Y de pronto gritos desgarradores, los de los monos aulladores rompieron todo este encantamiento. Una disputa, una discusión, un grito de amor nos revelaron la majestuosidad del silencio.",
   "page_home_title_p1_write"=>"I. Introducción de Musica Dominus",
   "page_home_date_p1_write"=>"27 Avril 2016",
   "page_home_body_p1_write"=>"¡Viajar no es una reacción de rebeldía del mundo sino más bien la necesidad de respirar! ¡Incluso parece que un viaje no se decide de inmediato o más bien no está programado! Despliegas tu hoja de ruta, la de toda América, se te acelera el corazón; la decisión e incluso la dirección, parece tomarse muy a menudo antes de encontrar la verdadera razón.
   En ese momento, en los años 80, aterricé en la costa oeste de los Estados Unidos, lleno de ambición. Antes llevaba una vida muy agradable, viviendo en un pequeño velero de 25 pies en el puerto de Antibes, en el sur de Francia. En cuanto empezó a soplar el mistral, barriendo con fuerza las nubes grises y el oleaje que nos llegaba del golfo de Génova, cogimos a mi novia y a mí, el timón hacia Saint-Tropez o las islas de Hyères. Para ganarnos la vida, teníamos un pequeño restaurante muy modesto.",
   "page_home_title_p2_write"=>"II. Significado Espiritual de Musica Dominus",
   "page_home_date_p2_write"=>"27 Avril 2016",
   "page_home_body_p2_write"=>"Si recibí una educación católica tradicional, reconozco que realmente no tuve una convicción muy profunda en mi juventud. Respeté y seguí esta religión enseñada por mi familia. Mi abuela era música, me llevó a los concursos Queen Elisabeth en Bruselas. Me asombraron los conciertos para piano de Ludwig von Beethoven interpretados por Emil Gilels, los nocturnos y polonesas de Frederic Chopin interpretados por Mauricio Polini y otro de Tchaikovsky, tocado con énfasis por este pianista ruso cuyo nombre he olvidado. Traté de reproducir estos sonidos extraordinarios en el piano negro de la mansión de mi abuelo. Descubrí los acordes que resonaban gracias a los altos techos de esta casa de piedra con sus columnas de mármol.",
   "page_home_more_write"=>"Ver más Galerías",


   //US
   "page_us_body_p0"=>"En todas las instituciones educativas y en muchas comunidades estamos presenciando actos de celos, acoso e intimidación. Los niños más sensibles son a menudo los objetivos. Yo mismo sufrí esta violencia verbal y psicológica cuando era niño. El estudio de la música clásica es la mejor manera, con la oración, de poder superar estos inconvenientes permitiendo al niño equilibrarse, encontrar su lugar en el mundo, desarrollarse pudiendo afirmarse. Como hemos visto en capítulos anteriores, la violencia excesiva y la vulgarización son los signos de nuestra sociedad decadente, materialista y egocéntrica.",
   "page_us_body_p1"=>"es una forma de reconectar con la enseñanza de los verdaderos valores a través del estudio de la Biblia, apta para niños de todas las edades, sobre el tema de la música antigua. Esta enseñanza la dedico a los más pobres, a los niños que no tienen la posibilidad de acceder a una educación musical de calidad, y mucho menos la de un instrumento clásico como el pianoforte.",
   "page_us_body_p2"=>"Con intensa atención y concentración, gracias a la meditación, el estudio y la interpretación de minuetos, sonatinas, arias por parte de jóvenes principiantes quedará grabado y accesible en su 'yo' más profundo, su verdadera naturaleza finalmente revelada por la música antigua. Esta presencia del Espíritu a su lado y camino al éxito, este “sentimiento de logro”, es la iluminación de un niño apartado por una mala orientación en la escuela, en la comunidad o simplemente deambulando por las calles.",
   "page_us_body_p3"=>"Quería terminar precisando que el piano, el rey de los instrumentos, reúne en sí mismo, en armonía, los instrumentos utilizados por el rey David y su corte durante las oraciones de los salmos. Recordemos que en la liturgia judía del Templo, la cadencia comandada por los instrumentos parecía tener más lugar que la melodía. La música servía sobre todo para dar ritmo a los diversos movimientos de la celebración con el tambor o la pandereta además de los címbalos. El cuerno, hecho con un cuerno de cabra, solía anunciar la presencia del Señor, combinándose armoniosamente con la lira, tocada por David.",
   "page_us_body_p4"=>"¡Todas las personas aplaudan! ¡Dios se levanta en aclamación, Yahveh en el sonido del cuerno! Salmo(47) 46, 1-6",
   "page_us_body_p5"=>"El piano acústico moderno es un instrumento de cuerda golpeada, el tablero armónico debe ser de madera de la mejor calidad. El metrónomo, marcando la cadencia es fundamental y los tres pedales permiten al joven músico aprender a expresarse, sin excesos, desde el piano al forte a través de la concentración, la meditación y el estudio diario.",
   "page_us_body_p6"=>"Por favor, ayúdanos a difundir el mensaje.",
   "page_us_body_p7"=>"Sus donaciones son bienvenidas y se invertirán en este objetivo.",

   "page_us_title_about"=>"Acerca de mí",
   "page_us_subtitle_about"=>"No hay amor para tomar, mientras que hay amor para acoger. Hay tanto amor para acoger como para dar y lo que hace el cristianismo es que todo se puede vivir en el modo de acoger y dar.",
   "page_us_p00_about"=>"Hola, antes que nada quería presentarme:",
   "page_us_p0_about"=>"Vincent Cambier ",
   "page_us_p1_about"=>"nacido el 10 de diciembre de 1957 en Ronse, una pequeña ciudad del reino de Bélgica, situada a pocos kilómetros de la frontera francesa, las localidades de Roubaix, Tourcoing y Lille son los más cercanos. Educación tradicional Católico, griego latino en el colegio de los jesuitas.",
   "page_us_p2_about"=>"Mi apellido 'de La Lozerie' viene de nuestros orígenes, cuando éramos ennoblecido como caballero en el siglo XIV. Lo uso en todos mis libros de aventuras de viajes, no por esnobismo ni pretensión, sólo que es más bonito y el El nombre Cambier es demasiado difícil de pronunciar en Estados Unidos.",
   "page_us_p3_about"=>"Juventud musical gracias a mi abuela materna: Lutgarde, de Tongres, en Limburgo, cerca de la frontera alemana.",
   "page_us_p4_about"=>"A los 20 salí de Europa rumbo a San Diego, California, en los Estados Unidos con Béatrice, la joven y bonita camarera del restaurante que habíamos creado en Antibes, en el sur de Francia. Todo el resto de mi juventud fue profundamente influenciado por la cultura norteamericana de los años 80: culto al cuerpo, belleza plástica y vida materialista. Muy rápidamente me convertí en el mejor vendedor de una agencia matrimonial, en la época en que no existían las computadoras. yo estaba conduciendo Cadillac y viajaba entre Newport Beach, Hollywood, Beverly Hills y La Jolla, la joya de California, un balneario al norte de San Diego o Tenía mi velero, un balandro de 30 pies, en el puerto de Mission Bay.",
   "page_us_p5_about"=>"El Jeannot de 25 pies, anclado en Port Vauban en Antibes donde dormíamos, Béatrice y yo, arrullados por las olas del Mediterráneo, ya estábamos lejos, como ella, a quien abandoné, prefiriendo las bellezas plásticas de las jóvenes americanas.",
   "page_us_p6_about"=>"A los 40 años, era periodista, escritor e incluso vendedor de publicidad para una revista de vino y gastronomía en Cannes, en los Alpes Marítimos en Francia. Unos años después fui invitado por la aerolínea nacional de Chile así como por algunos grandes comerciantes productores de vinos de este región del nuevo mundo. Cómodamente instalado en la lujosa suite del último piso del hotel Crowne Plaza en Santiago de Chile, donde jugué billar con el chef suizo, pude degustar la cocina exótica, asombrado por las jovencitas latinas de tez dorada del barrio de Bella Vista, el distrito bohemio de ciudad capital. A raíz de este reportaje sobre los vinos del nuevo mundo, volví a California, invitado por la Asociación de Vinos de los Valles de Napa y Sonoma.",
   "page_us_p7_about"=>"Posteriormente me radiqué en el estado de Arizona, en Estados Unidos, donde creé mi propia línea de fragancias y cosméticos para el hogar: 'La Lozerie en Provence', fabricado por la familia Grangeon establecida en St Rémy de Provence. Esta fueron los mejores años: diez años de trabajo sin tomar vacaciones, compartidos entre el sur de Francia y toda América del Norte. A bordo del Dodge RAM y su inolvidable motor V8 de 5 litros, que sacó sin esfuerzo un Remolque Pace American de 10 por seis pies, que se duplicó como mi oficina y litera. Con este vehículo conduciendo por las interestatales, he conocido casi todos los estados: Nueva Inglaterra, Georgia, Texas, Medio Oeste, Chicago y Illinois, Michigan, Colorado y Utah, la frontera de Canadá, Seattle y Vancouver, toda California que conocía bien, Arizona y Luisiana donde pude hablar francés con los últimos negros americanos de Nouvelle Orleans, La Fayette y Bâton Rouge, amigas afroamericanas que han mantenido los verdaderos valores del pasado y la cultura de sus ancestros.",
   "page_us_p8_about"=>"La crisis económica de 2018 y 2019, la caída de los dos países más grandes bancos y prestamistas hipotecarios en los Estados Unidos marcaron el final de la Sueño americano, creado por la era Clinton y su espejismo financiero. En unas pocas semanas, perdí un tercio de mi clientela que ya no podía honrar las facturas de sus pedidos pasaban a 'La Lozerie en Provence' que estaba perdiendo poco más de cien mil dólares. Demasiado duro para subir la pendiente... Asqueado por un sistema que estaba matando a los pequeños empresarios, ahora los peces gordos de multinacionales, decidí cruzar la frontera con México, enviando por la ventanilla abierta del Dodge, volando los cheques rebotados, 'los cheques madera' y facturas impagas. Tanto para la ecología.",
   "page_us_p9_about"=>"Dentro de unos meses, desde lo de Nogales en México, habré cruzado diez fronteras: Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panamá, Colombia, Ecuador, Perú, Chile o el motor V8 recalentado en el desierto de el Atacama. Reparado en Paraguay, por un mecánico argentino, pude continuar un viaje que parecía no tener fin. cruzando el Brasil, Guayana Francesa, Surinam, Guayana, Boa Vista: la puerta entrada al Amazonas, norte de Brasil, atravesando Venezuela en pleno crisis económica, llegué, a duras penas, a Cúcuta, en Colombia ¡el otro lado! Un tercer viaje me hizo descubrir Ayacucho, Arequipa en Perú, Bolivia Cultura Nativa Americana, Lago Titicaca, Jujuy Argentina, Tilcara, San Juan, camino fronterizo de los Andes: el paso de Jama, Antofagasta, Arica en Chile, Lago Chungara, San Pedro y el Valle de Azapa o Mecánicos peruanos pudieron armar la nueva motorhome, proveniente de Estados Unidos Unidos, durante los dos años de la pandemia cuando las fronteras estuvieron cerradas. Gracias a la hospitalidad de Niksa Bezmalinovic, una de las últimas granjeras de este valle desértico donde pude vivir en el sencillo remolque que también había elegido este olivar del desierto para su renovación total. Así nació la casa rodante que ven en la foto: una camioneta Ford de Valparaíso, una el registro mixto de Chile y Arizona, EE. UU., donde se fabricó.",
   "page_us_p10_about"=>"Desde San Diego, EE.UU. a Sao Francisco, Brasil:",
   "page_us_p11_about"=>"A lo largo de estos viajes, he soportado tantas penalidades: desde la rotura de ballestas, dos perdidas de ruedas, rodando solo! En la inmensidad de gran sabana venezolana, guardabarros desgarrados y hundidos en los golpes, neumáticos, junta de culata que frió dos veces dos motores: el motor Ram original de Dodge Chrysler, un MWM turbo diesel instalado en el Paraguay, de cinturones hechos trizas… Los momentos más duros fueron la rotura en la pista de tierra entre el Amazonas de Guyana y Brasil, las cuatro ruedas de el tráiler robado en Nochebuena del parking de la parroquia de San Félix, en el centro de Venezuela, los controles de la policía militar de Brasil y la La corrupta Guardia Nacional de Venezuela 'controla' los arrestos de Paramilitares de El Salvador, los caminos sin barreras de seguridad se entrecruzan y con vistas al pacífico en Perú, las protestas de los años 2009 en el Honduras…los caminos con bisagras de México…y los niños mendigos porque tienen hambre. Pero lo que hace la fuerza de un viajero es esta voluntad interior que siempre te empuja a seguir adelante, a ir más allá.",
   "page_us_p12_about"=>"Estos años de viajes de aventura me han enseñado que en San Diego, California, Yo no era un hombre libre. Yo era un esclavo de mi vida materialista y egoísta. Desde 'siempre queriendo más y más bella'. Ahora que perdí a mi padre tierra, sé que nuestro Padre espiritual, el Creador de todo este universo, no no creó una libertad, porque creó al Hombre con la libertad de hacerse libre él mismo. La verdadera libertad no se encuentra en las playas de Panamá ni en las de Costa Rica, ni en la gran sabana, en brazos de una linda venezolana. El la libertad es libertad sólo si uno mismo la crea. Porque la voz de la naturaleza hace resonar constantemente en el hombre una llamada a vivir no para Dios y para el otros hombres sino para sí mismo, egoístamente, como los demás seres de la naturaleza que vive según su instinto. Documentándome y leyendo los libros. los libros espirituales de mi padre, escritos por François Varillon y Maurice Zundel, entendido que hay en el hombre (y en la mujer) una doble fuerza: por un lado, una fuerza de la gravedad y la inercia que lo invita a renunciar a ser un hombre libre y el empuja a vivir como los demás seres del mundo que no tienen libertad para construir. Y por otro lado, una fuerza ascendente que lo invita a construir su libertad a la que Dios, por gracia, dará acceso incluso a su propia libertad. La verdad la libertad se encuentra en la divinidad, acogiendo a Cristo en el corazón de uno por viviendo según su ejemplo, negándose a sí mismo. Dos grandes ejemplos hombres libres fueron Francisco de Asís o Carlos de Foucault, que lideraron sus vidas compartiendo con los demás y viviendo para los demás. tan pequeño de nosotros, simples pecadores, podemos alcanzar tal nivel de santidad y divinidad, es necesario que modifiquemos nuestro comportamiento hacia los demás. Porque la característica del pecado es desencadenar un tren de olas que perturban el relaciones humanas. Cualquier mala acción o pensamiento es una provocación al mal que depositamos en la conciencia de los demás.",
   "page_us_p13_about"=>"No hay amor para tomar, mientras que hay amor para acoger. Hay tanto amor para acoger como para dar y lo que hace el cristianismo es que todo se puede vivir en el modo de acoger y dar.",
   "page_us_p14_about"=>"A los que tendrían dificultades para vivir según estos preceptos en nuestra vida de todos los días, esta sociedad brutal, decadente y corrompida por el vicio y egoísmo, se debe explorar la opción de ir a vivir en comunidad.",
   "page_us_p15_about"=>"Personalmente, como escritor de viajes, descubrí la libertad al poder dar más 'de mí mismo', en tareas como profesor voluntario de lenguas en las comunidades amerindias Misak de Colombia, la los quichuas de Ecuador, Perú, los guaraníes de Paraguay, Venezuela, los niños indígenas en el Amazonas en Guyana, en Boa Vista en el norte de Brasil, en ayudar a los frailes franciscanos tanto en Río de Janeiro como en Panamá, en el comunidades cafetaleras del volcán Barú.",
   "page_us_p16_about"=>"Si estudio y enseño música barroca, también llamada música sacra, es que el piano clásico se ha convertido en el vector esencial de mi estrecha relación con el Padre Celestial. Es para mí, la forma trascendental hacia el Creador.",
   "page_us_p17_about"=>"Habiendo estudiado, sin profundizar en ellas, las técnicas orientales de la medicina, he sido capaz de entender que la forma de comer juega un papel importante en la comportamiento humano.",
   "page_us_p18_about"=>"You are what you eat",
   "page_us_p19_about"=>"…Eres lo que comes, un dicho muy conocido de un filósofo griego. Agregaré: dependiendo de lo que comas y cómo sobrio en el comer, como en la dieta macrobiótica o vegana, construye un lugar de paz dentro de ti. Todo en la tierra y en el universo. existe en oposición complementaria. Viviendo en un mundo bañado en acidez extrema (comida degradada, vulgaridad, egoísmo, contaminación acústica, contaminación del aire, del agua y de la mente), es necesario equilibrar comiendo cereales, plantas, frutas, que yo denominaremos: dieta alcalina. Recomiendo una dieta 80% alcalina (YIN). y 20% de ácido (YANG). Las personas serán más fácilmente reconocidas. vegetarianos en su estilo de vida no agresivo y en su relación con los demás.",
   "page_us_p20_about"=>"En nuestro mundo, ¿no sigue siendo el símbolo la cruz? El hombre dividido entre una fuerza ascendente, la llamada de Dios a compartir el amor y una fuerza que tira por el camino de la servidumbre hacia su supuesta libertad. y un equilibrio entre YIN y YANG, alteración entre alcalino y ácido.",

   //Write
   "page_home_title_p3_write"=>"III. Razones para Estudiar Música Antigua en el Piano",
   "page_home_date_p3_write"=>"27 Avril 2016",
   "page_home_body_p3_write"=>"Para eso estudiar al piano, obras escritas por compositores barrocos, tan antiguos, a caballo entre el Renacimiento y el Clásico. 1. Equilibrio armónico. Para principiantes, en su mayoría niños: requiere que operes ambas partes del cerebro. La parte izquierda del cerebro corresponde a la lógica, procesará el aspecto funcional y matemático de la música, como la división de los sonidos en medias notas, negras, corcheas, semicorcheas, etc. ¡El lado derecho del cerebro se ocupará del arte, la melodía, el canto! ¡Porque no olvidemos que tocar el piano es simplemente hacer cantar a tu instrumento! Consiguiendo coordinar las dos manos conseguiremos la armonía. Es casi una lucha entre la cabeza (mano izquierda) y el corazón (mano derecha) entre la expansión melódica y la tensión rítmica, entre la estructura y el ensueño. Lo más interesante",
   "page_home_title_p4_write"=>"IV. Musicoterapia y Psicología",
   "page_home_date_p4_write"=>"27 Avril 2016",
   "page_home_body_p4_write"=>"Esta información nos la proporcionaron periódicos de los Estados Unidos. Media hora de música clásica al día: es obligatorio para todos los niños en Florida, Estados Unidos. Apodado el Proyecto de Ley de los Bebés de Beethoven, el Proyecto de Ley 660 no solo pretende ayudar a los más pequeños a dormirse a la hora de la siesta, sino que también pretende estimular su desarrollo cerebral de forma armoniosa... En Francia, la acción benéfica de la música no es del todo desconocida. En los hospitales Armand-Trousseau y Necker de París, las salas de preanestesia infantil se han convertido en auténticas salas de conciertos: niños, padres y personal de enfermería pueden manipular instrumentos, descubrir sonidos, improvisar o escuchar casetes. Después de este condicionamiento, un músico acompaña al niño al quirófano haciendo resonar en el laberinto de pasillos, ascensores y otros lugares fríos desconocidos, sonidos armoniosos y tranquilizadores. Los resultados son concluyentes ya que la música juega un papel positivo en el éxito de la anestesia y ayuda a los niños a sobrellevar mejor el trauma de su estancia hospitalaria.",
   "page_home_title_p5_write"=>"V. Mi Camino como Maestro",
   "page_home_date_p5_write"=>"27 Avril 2016",
   "page_home_body_p5_write"=>"Mi viaje como maestra voluntaria en comunidades nativas americanas. En el norte de América, me fascinaron los sioux, los navajos, en las grandes llanuras, los cheyenne en el sureste, los apaches en el suroeste. Pude visitar las reservas, intercambiar ideas con muchos de ellos. Hablan tantos dialectos diferentes como toda la población amerindia de Colombia. A diferencia de los viajeros turísticos en avión que conocen mucho más de las capitales de los países que visitan, estando cerca el aeropuerto y cómodos hoteles internacionales; personalmente, humilde viajero de caminos, sin horarios, sin constricciones, sin entender bien el objetivo de los viajes organizados, poco a poco comencé a sentirme invadido por este dulce salvajismo primitivo. Me sentí más cercano a los nativos que a la mayoría blanca de estos pequeños países centroamericanos. Con ellos aprendí a vivir de la forma más sencilla posible, en contacto con la naturaleza y tratando de saborear todo, especialmente el silencio. No me gusta hablar de pobreza; sino vivir de los productos frescos de la tierra, al ritmo de las estaciones, de sus buenas o malas cosechas. ¡La dureza de las condiciones y los caprichos del clima dan ganas de clamar justicia!",
   
   //footer
   "footer_text"=>"Necesitamos de tu apoyo en donación para que este proyecto siga Aportando al Mundo.",
   "footer_button"=>"Apóyanos",
   "footer_copyright"=>"© Musica Dominus. 2022 Todos los derechos Reservados."

];